services:
  rapp:
    build:
      context: .
      dockerfile: rapp.Dockerfile
    volumes:
      - /tmp:/tmp
    environment:
      - GREENRAN_STATE_DIR=/tmp

  flexric-energy:
    build:
      context: .
      dockerfile: flexric.Dockerfile
    volumes:
      - /tmp:/tmp

  app2-simulator:
    build:
      context: .
      dockerfile: rapp.Dockerfile
    command: ["python3", "/app/apps/app2_monitoramento/backend/simulate_sensors.py", "--num-sensors", "20", "--interval", "2.0"]
    volumes:
      - /tmp:/tmp
