#!/usr/bin/env python3
"""
Train a GraphSAGE-style graph reconstructor on completed conflitos datasets.

This script is the first practical step after the collection protocol:

- it consumes the `50`, `150`, and `450` conflict subsets generated by
  `scripts/run_experimentos_conflitos.py`;
- it builds node features from the exported conflict CSV;
- it builds a support graph from row-level node co-occurrence;
- it trains a GraphSAGE-style encoder plus a link predictor to reconstruct the
  scenario conflict graph;
- it reports reconstruction precision/recall/F1 across an epoch sweep.

The goal is to align the GreenRAN pipeline with the next methodological step of
`conflitos`: training a graph learner after the `50/150/450` datasets have been
collected.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import random
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import torch
import torch.nn as nn
import torch.nn.functional as F

from training.graphsage_report_utils import load_scenario_reports


DEFAULT_EXPERIMENT_ROOT = PROJECT_ROOT / "runs" / "experimentos_conflitos"
DEFAULT_OUTPUT_STEM = "graphsage_training"
DEFAULT_EPOCHS = (50, 100, 200, 400, 600, 800, 1000)
DEFAULT_SUBSET_SIZES = (50, 150, 450)
NODE_TYPES = ("agent", "parameter", "kpi", "service", "mitigation", "arbiter", "unknown")
ALLOWED_TYPE_PAIRS = {
    ("agent", "parameter"),
    ("parameter", "kpi"),
    ("kpi", "service"),
    ("kpi", "agent"),
    ("kpi", "arbiter"),
    ("agent", "mitigation"),
    ("arbiter", "mitigation"),
    ("mitigation", "service"),
}
RELATION_TYPES = ("controls", "affects", "belongs_to", "triggers_arbitration", "mitigates", "protects")
RELATION_BY_TYPE_PAIR = {
    ("agent", "parameter"): "controls",
    ("parameter", "kpi"): "affects",
    ("kpi", "service"): "belongs_to",
    ("kpi", "agent"): "triggers_arbitration",
    ("kpi", "arbiter"): "triggers_arbitration",
    ("agent", "mitigation"): "mitigates",
    ("arbiter", "mitigation"): "mitigates",
    ("mitigation", "service"): "protects",
}
ROLE_FIELDS = {
    "source_agent": "source_agent",
    "target_agent": "target_agent",
    "parameter": "parameter",
    "affected_service": "service",
    "affected_kpi": "kpi",
    "mitigation_action": "mitigation",
    "latest_energy_command": "energy_command",
}
NUMERIC_FIELDS = (
    "observed_value",
    "threshold_value",
    "observed_delta_from_threshold",
    "cvar_ms",
    "p95_ms",
    "throughput_mbps",
    "global_packet_loss_percent",
    "latest_power_percent",
    "rapp_confidence",
    "ml_confidence",
)
CONFLICT_TYPES = ("direct", "indirect", "implicit", "unknown")
DEFAULT_ARBITER_ID = "rApp-ResourceOptimizer"
NODE_TYPE_PREFIXES = {
    "agent": "agent",
    "parameter": "param",
    "kpi": "kpi",
    "service": "svc",
    "mitigation": "mit",
    "arbiter": "arb",
    "unknown": "unk",
}
DOMAIN_SCOPES = ("mixed", "app1", "app2", "app3")
DOMAIN_SCOPE_MODES = ("auto", "service", "causal")


@dataclass
class TrainingCase:
    scenario: str
    subset_size: int
    dataset_path: Path
    graph_path: Path
    scenario_dir: Path
    output_dir: Path


@dataclass
class RoundSplit:
    mode: str
    train_rows: list[dict]
    test_rows: list[dict]
    train_rounds: list[int]
    test_rounds: list[int]
    contributing_rounds: list[int]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a GraphSAGE-style reconstructor on conflitos experiment outputs."
    )
    parser.add_argument(
        "--dataset-path",
        help="direct CSV dataset path; bypasses experiment report discovery when paired with --graph-path",
    )
    parser.add_argument(
        "--graph-path",
        help="direct graph JSON path; bypasses experiment report discovery when paired with --dataset-path",
    )
    parser.add_argument(
        "--scenario-label",
        default="direct_dataset",
        help="scenario label used in direct dataset mode",
    )
    parser.add_argument(
        "--experiment-dir",
        help="completed experiment directory; defaults to the latest one under runs/experimentos_conflitos",
    )
    parser.add_argument(
        "--scenario",
        action="append",
        dest="scenarios",
        default=[],
        help="scenario slug to train; may be passed multiple times",
    )
    parser.add_argument(
        "--subset-sizes",
        default="50,150,450",
        help="comma-separated subset sizes to train",
    )
    parser.add_argument(
        "--epochs",
        default="50,100,200,400,600,800,1000",
        help="comma-separated epoch checkpoints; training runs until the maximum value",
    )
    parser.add_argument("--hidden-dim", type=int, default=16, help="hidden dimension for GraphSAGE")
    parser.add_argument("--embed-dim", type=int, default=16, help="embedding dimension for GraphSAGE")
    parser.add_argument("--dropout", type=float, default=0.10, help="dropout rate")
    parser.add_argument("--learning-rate", type=float, default=0.001, help="optimizer learning rate")
    parser.add_argument("--weight-decay", type=float, default=1e-4, help="optimizer weight decay")
    parser.add_argument("--threshold", type=float, default=0.5, help="edge threshold for reconstruction")
    parser.add_argument(
        "--loss-mask-mode",
        choices=("all", "support"),
        default="all",
        help="which candidate pairs participate in the training loss; 'support' limits loss to observed support pairs plus positives",
    )
    parser.add_argument(
        "--negative-edge-weight",
        type=float,
        default=1.0,
        help="multiplier applied to negative-edge loss terms",
    )
    parser.add_argument(
        "--pos-weight-scale",
        type=float,
        default=1.0,
        help="scale applied to the automatic positive-class weight",
    )
    parser.add_argument(
        "--max-pos-weight",
        type=float,
        default=0.0,
        help="optional cap for the automatic positive-class weight; 0 disables the cap",
    )
    parser.add_argument(
        "--fp-penalty-weight",
        type=float,
        default=0.0,
        help="extra penalty on negative edges whose predicted probability exceeds --fp-penalty-margin",
    )
    parser.add_argument(
        "--fp-penalty-margin",
        type=float,
        default=0.5,
        help="probability margin used by --fp-penalty-weight on negative edges",
    )
    parser.add_argument(
        "--selection-mode",
        choices=("f1", "fp_penalized"),
        default="f1",
        help="criterion used to choose the best checkpoint",
    )
    parser.add_argument(
        "--selection-fp-weight",
        type=float,
        default=0.25,
        help="false-positive penalty weight used when --selection-mode=fp_penalized",
    )
    parser.add_argument(
        "--selection-precision-weight",
        type=float,
        default=0.10,
        help="precision bonus weight used when --selection-mode=fp_penalized",
    )
    parser.add_argument(
        "--pair-mask-mode",
        choices=("all", "valid_types"),
        default="valid_types",
        help="candidate edge pairs used in training/evaluation; 'valid_types' restricts pairs to semantically valid node-type chains",
    )
    parser.add_argument(
        "--domain-scope",
        choices=DOMAIN_SCOPES,
        default="mixed",
        help="optional supervision scope; app1/app2/app3 restrict training and evaluation to domain-specific structural pairs",
    )
    parser.add_argument(
        "--domain-scope-mode",
        choices=DOMAIN_SCOPE_MODES,
        default="auto",
        help="how domain rows are selected; 'auto' uses service for app1 and causal for app2/app3, while explicit 'service' or 'causal' force that policy",
    )
    parser.add_argument("--seed", type=int, default=42, help="random seed")
    parser.add_argument(
        "--split-by-rounds",
        action="store_true",
        help="train on the first rounds that compose each subset and evaluate on held-out final rounds",
    )
    parser.add_argument(
        "--test-round-fraction",
        type=float,
        default=0.30,
        help="fraction of contributing rounds reserved for evaluation when --split-by-rounds is enabled",
    )
    parser.add_argument(
        "--min-test-rounds",
        type=int,
        default=1,
        help="minimum number of held-out rounds when --split-by-rounds is enabled",
    )
    parser.add_argument(
        "--train-rounds",
        help="manual train rounds as comma-separated values/ranges, for example 1-34,35",
    )
    parser.add_argument(
        "--test-rounds",
        help="manual test rounds as comma-separated values/ranges, for example 36-38",
    )
    parser.add_argument(
        "--output-dir",
        help="directory where training artifacts will be written; defaults to <experiment>/graphsage_training",
    )
    parser.add_argument(
        "--init-model",
        help="optional checkpoint path used to warm-start model weights before training",
    )
    parser.add_argument(
        "--direct-test-fraction",
        type=float,
        default=0.25,
        help="fraction of rows reserved for evaluation in direct dataset mode",
    )
    parser.add_argument(
        "--direct-min-test-rows",
        type=int,
        default=1,
        help="minimum held-out rows in direct dataset mode",
    )
    return parser.parse_args()


def latest_experiment_dir(root: Path) -> Path:
    candidates = sorted(root.glob("*/experiment_report.json"))
    if not candidates:
        raise FileNotFoundError(f"no completed experiment_report.json found under {root}")
    return candidates[-1].parent


def load_json(path: Path) -> dict:
    with path.open() as f:
        return json.load(f)


def read_csv_rows(path: Path) -> list[dict]:
    with path.open() as f:
        return list(csv.DictReader(f))


def read_round_summary(path: Path) -> list[dict]:
    with path.open() as f:
        rows = list(csv.DictReader(f))
    for row in rows:
        row["round"] = int(row["round"])
        row["rows"] = int(row["rows"])
        row["cumulative_rows"] = int(row.get("cumulative_rows", 0) or 0)
    return rows


def normalize_node_value(value: str | None, fallback: str) -> str:
    normalized = (value or fallback).strip()
    return normalized or fallback


def target_node_type(target: str) -> str:
    return "arbiter" if target.startswith("rApp-") or target == DEFAULT_ARBITER_ID else "agent"


def qualified_node_id(node_type: str, raw_value: str) -> str:
    prefix = NODE_TYPE_PREFIXES.get(node_type, NODE_TYPE_PREFIXES["unknown"])
    return f"{prefix}:{raw_value}"


def contains_vehicle_signal(value: str | None) -> bool:
    text = (value or "").strip().lower()
    return "vehicle" in text or "veicular" in text


def resolve_domain_scope_mode(domain_scope: str, scope_mode: str) -> str:
    if scope_mode != "auto":
        return scope_mode
    if domain_scope == "app1":
        return "service"
    if domain_scope in {"app2", "app3"}:
        return "causal"
    return "service"


def infer_row_domain(row: dict, scope_mode: str = "service") -> str:
    affected_service = normalize_node_value(row.get("affected_service"), "")
    affected_kpi = normalize_node_value(row.get("affected_kpi"), "")
    source_agent = normalize_node_value(row.get("source_agent"), "")
    target_agent = normalize_node_value(row.get("target_agent"), "")
    parameter = normalize_node_value(row.get("parameter"), "")

    if scope_mode == "service":
        if (
            affected_service == "App3-Veicular"
            or contains_vehicle_signal(affected_kpi)
        ):
            return "app3"
        if affected_service == "App2-Monitoramento" or "app2_" in affected_kpi.lower():
            return "app2"
        if affected_service == "App1-Vigilancia" or "camera_" in affected_kpi.lower():
            return "app1"
        return "mixed"

    if (
        parameter == "vehicle_priority_policy"
        or contains_vehicle_signal(source_agent)
        or contains_vehicle_signal(target_agent)
    ):
        return "app3"
    if "EnergySaver" in source_agent or parameter == "energy_policy":
        return "app2"
    if "RANSlicer" in source_agent or parameter == "global_health_policy":
        return "app1"
    return "mixed"


def safe_float(value: str | None) -> float:
    try:
        if value in (None, ""):
            return 0.0
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def normalize_conflict_type(value: str | None) -> str:
    text = (value or "").strip().lower()
    if text in {"direct", "indirect", "implicit"}:
        return text
    return "unknown"


def parse_int_tuple(raw: str) -> tuple[int, ...]:
    return tuple(sorted({int(piece.strip()) for piece in raw.split(",") if piece.strip()}))


def parse_round_list(raw: str) -> list[int]:
    values = set()
    for piece in raw.split(","):
        token = piece.strip()
        if not token:
            continue
        if "-" in token:
            start_text, end_text = token.split("-", 1)
            start = int(start_text.strip())
            end = int(end_text.strip())
            if end < start:
                raise SystemExit(f"invalid round range '{token}'")
            values.update(range(start, end + 1))
        else:
            values.add(int(token))
    return sorted(values)


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def set_seed(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def selected_reports(experiment_dir: Path, slugs: list[str]) -> list[dict]:
    scenario_reports = load_scenario_reports(experiment_dir)
    if not slugs:
        return scenario_reports

    selected = []
    known = {entry["scenario"] for entry in scenario_reports}
    for slug in slugs:
        if slug not in known:
            raise SystemExit(f"scenario '{slug}' not found in {experiment_dir}")
        selected.extend(entry for entry in scenario_reports if entry["scenario"] == slug)
    return selected


def build_cases(
    experiment_dir: Path,
    scenario_reports: list[dict],
    subset_sizes: tuple[int, ...],
    output_root: Path,
) -> list[TrainingCase]:
    cases = []
    for report in scenario_reports:
        graph_path = Path(report["full_export"]["graph_path"])
        subset_map = {entry["requested_rows"]: entry for entry in report.get("subsets", [])}
        for subset_size in subset_sizes:
            subset = subset_map.get(subset_size)
            if subset is None:
                continue
            dataset_path = Path(subset["dataset_path"])
            output_dir = output_root / report["scenario"] / f"subset_{subset_size}"
            cases.append(
                TrainingCase(
                    scenario=report["scenario"],
                    subset_size=subset_size,
                    dataset_path=dataset_path,
                    graph_path=graph_path,
                    scenario_dir=experiment_dir / report["scenario"],
                    output_dir=output_dir,
                )
            )
    if not cases:
        raise SystemExit("no training cases found for the requested scenarios/subsets")
    return cases


def build_direct_case(
    dataset_path: Path,
    graph_path: Path,
    scenario_label: str,
    output_root: Path,
) -> list[TrainingCase]:
    if not dataset_path.exists():
        raise FileNotFoundError(f"dataset not found: {dataset_path}")
    if not graph_path.exists():
        raise FileNotFoundError(f"graph not found: {graph_path}")

    rows = read_csv_rows(dataset_path)
    output_dir = output_root / scenario_label
    return [
        TrainingCase(
            scenario=scenario_label,
            subset_size=len(rows),
            dataset_path=dataset_path,
            graph_path=graph_path,
            scenario_dir=dataset_path.parent,
            output_dir=output_dir,
        )
    ]


def build_target_adjacency(graph: dict, node_ids: list[str], node_index: dict[str, int]) -> torch.Tensor:
    target = torch.zeros((len(node_ids), len(node_ids)), dtype=torch.float32)
    for edge in graph.get("edges", []):
        source = edge.get("source")
        target_node = edge.get("target")
        if source not in node_index or target_node not in node_index:
            continue
        target[node_index[source], node_index[target_node]] = 1.0
    return target


def build_conflict_type_target_adjacency(
    graph: dict,
    node_ids: list[str],
    node_index: dict[str, int],
    conflict_type: str,
    min_support: int = 1,
) -> torch.Tensor:
    target = torch.zeros((len(node_ids), len(node_ids)), dtype=torch.float32)
    for edge in graph.get("edges", []):
        source = edge.get("source")
        target_node = edge.get("target")
        conflict_types = edge.get("conflict_types", {}) or {}
        if source not in node_index or target_node not in node_index:
            continue
        support = conflict_types.get(conflict_type)
        if support is None:
            continue
        if safe_float(support) < float(min_support):
            continue
        if conflict_type in conflict_types:
            target[node_index[source], node_index[target_node]] = 1.0
    return target


def build_graph_from_rows(rows: list[dict]) -> dict:
    nodes: dict[str, dict[str, Any]] = {}
    edges: dict[tuple[str, str, str], dict[str, Any]] = {}

    def add_node(node_id: str, node_type: str) -> None:
        if node_id not in nodes:
            raw_label = node_id.split(":", 1)[1] if ":" in node_id else node_id
            nodes[node_id] = {
                "id": node_id,
                "label": raw_label,
                "type": node_type,
                "event_count": 0,
            }
        nodes[node_id]["event_count"] += 1

    def add_edge(source: str, target: str, relation: str, row: dict) -> None:
        key = (source, target, relation)
        if key not in edges:
            edges[key] = {
                "source": source,
                "target": target,
                "relation": relation,
                "weight": 0,
                "conflict_types": {},
                "affected_kpis": {},
            }
        edge = edges[key]
        edge["weight"] += 1
        conflict_type = normalize_conflict_type(row.get("conflict_type"))
        edge["conflict_types"][conflict_type] = int(edge["conflict_types"].get(conflict_type, 0)) + 1
        affected_kpi = (row.get("affected_kpi") or "unknown_kpi").strip() or "unknown_kpi"
        edge["affected_kpis"][affected_kpi] = int(edge["affected_kpis"].get(affected_kpi, 0)) + 1

    for row in rows:
        raw_source = normalize_node_value(row.get("source_agent"), "unknown_agent")
        raw_target = normalize_node_value(row.get("target_agent"), DEFAULT_ARBITER_ID)
        raw_parameter = normalize_node_value(row.get("parameter"), "unknown_parameter")
        raw_service = normalize_node_value(row.get("affected_service"), "unknown_service")
        raw_kpi = normalize_node_value(row.get("affected_kpi"), "unknown_kpi")
        raw_mitigation = normalize_node_value(row.get("mitigation_action"), "NONE")
        resolved_target_type = target_node_type(raw_target)

        source = qualified_node_id("agent", raw_source)
        target = qualified_node_id(resolved_target_type, raw_target)
        parameter = qualified_node_id("parameter", raw_parameter)
        service = qualified_node_id("service", raw_service)
        kpi = qualified_node_id("kpi", raw_kpi)
        mitigation = qualified_node_id("mitigation", raw_mitigation)

        add_node(source, "agent")
        add_node(target, resolved_target_type)
        add_node(parameter, "parameter")
        add_node(service, "service")
        add_node(kpi, "kpi")
        add_node(mitigation, "mitigation")

        add_edge(source, parameter, "controls", row)
        add_edge(parameter, kpi, "affects", row)
        add_edge(kpi, service, "belongs_to", row)
        add_edge(kpi, target, "triggers_arbitration", row)
        add_edge(target, mitigation, "mitigates", row)
        add_edge(mitigation, service, "protects", row)

    return {
        "nodes": sorted(nodes.values(), key=lambda item: (item["type"], item["id"])),
        "edges": sorted(edges.values(), key=lambda item: (item["source"], item["target"], item["relation"])),
    }


def build_support_matrix(rows: list[dict], node_index: dict[str, int]) -> torch.Tensor:
    support = torch.zeros((len(node_index), len(node_index)), dtype=torch.float32)

    def connect(left: str, right: str) -> None:
        if not left or not right:
            return
        if left not in node_index or right not in node_index:
            return
        li = node_index[left]
        ri = node_index[right]
        support[li, ri] += 1.0
        support[ri, li] += 1.0

    for row in rows:
        raw_source = normalize_node_value(row.get("source_agent"), "unknown_agent")
        raw_target = normalize_node_value(row.get("target_agent"), DEFAULT_ARBITER_ID)
        raw_parameter = normalize_node_value(row.get("parameter"), "unknown_parameter")
        raw_service = normalize_node_value(row.get("affected_service"), "unknown_service")
        raw_kpi = normalize_node_value(row.get("affected_kpi"), "unknown_kpi")
        raw_mitigation = normalize_node_value(row.get("mitigation_action"), "NONE")
        source = qualified_node_id("agent", raw_source)
        target = qualified_node_id(target_node_type(raw_target), raw_target)
        parameter = qualified_node_id("parameter", raw_parameter)
        service = qualified_node_id("service", raw_service)
        kpi = qualified_node_id("kpi", raw_kpi)
        mitigation = qualified_node_id("mitigation", raw_mitigation)

        # Keep support aligned with the intended causal chain instead of
        # building a full clique for every row, which over-connects hubs and
        # inflates false positives during reconstruction.
        connect(source, parameter)
        connect(parameter, kpi)
        connect(kpi, service)
        connect(kpi, target)
        connect(target, mitigation)
        connect(mitigation, service)
    return support


def build_valid_pair_mask(graph: dict, node_ids: list[str]) -> torch.Tensor:
    node_types = {node.get("id"): node.get("type", "unknown") for node in graph.get("nodes", [])}
    mask = torch.zeros((len(node_ids), len(node_ids)), dtype=torch.bool)
    for src_idx, source in enumerate(node_ids):
        source_type = node_types.get(source, "unknown")
        for dst_idx, target in enumerate(node_ids):
            if src_idx == dst_idx:
                continue
            target_type = node_types.get(target, "unknown")
            if (source_type, target_type) in ALLOWED_TYPE_PAIRS:
                mask[src_idx, dst_idx] = True
    return mask


def build_domain_pair_mask(
    graph: dict,
    rows: list[dict],
    node_ids: list[str],
    domain_scope: str,
    domain_scope_mode: str,
) -> torch.Tensor:
    mask = torch.zeros((len(node_ids), len(node_ids)), dtype=torch.bool)
    if domain_scope == "mixed":
        return mask

    resolved_scope_mode = resolve_domain_scope_mode(domain_scope, domain_scope_mode)
    node_index = {node_id: idx for idx, node_id in enumerate(node_ids)}
    node_types = {node.get("id"): node.get("type", "unknown") for node in graph.get("nodes", [])}
    domain_nodes: set[str] = set()

    for row in rows:
        if infer_row_domain(row, resolved_scope_mode) != domain_scope:
            continue

        raw_source = normalize_node_value(row.get("source_agent"), "unknown_agent")
        raw_target = normalize_node_value(row.get("target_agent"), DEFAULT_ARBITER_ID)
        raw_parameter = normalize_node_value(row.get("parameter"), "unknown_parameter")
        raw_service = normalize_node_value(row.get("affected_service"), "unknown_service")
        raw_kpi = normalize_node_value(row.get("affected_kpi"), "unknown_kpi")
        raw_mitigation = normalize_node_value(row.get("mitigation_action"), "NONE")

        source = qualified_node_id("agent", raw_source)
        target = qualified_node_id(target_node_type(raw_target), raw_target)
        parameter = qualified_node_id("parameter", raw_parameter)
        service = qualified_node_id("service", raw_service)
        kpi = qualified_node_id("kpi", raw_kpi)
        mitigation = qualified_node_id("mitigation", raw_mitigation)

        domain_nodes.update((source, target, parameter, service, kpi, mitigation))

    for src_node in domain_nodes:
        if src_node not in node_index:
            continue
        src_idx = node_index[src_node]
        src_type = node_types.get(src_node, "unknown")
        for dst_node in domain_nodes:
            if dst_node not in node_index or src_node == dst_node:
                continue
            dst_type = node_types.get(dst_node, "unknown")
            if (src_type, dst_type) not in ALLOWED_TYPE_PAIRS:
                continue
            dst_idx = node_index[dst_node]
            mask[src_idx, dst_idx] = True

    return mask


def build_relation_index_matrix(graph: dict, node_ids: list[str]) -> torch.Tensor:
    node_types = {node.get("id"): node.get("type", "unknown") for node in graph.get("nodes", [])}
    relation_to_idx = {name: idx for idx, name in enumerate(RELATION_TYPES)}
    relation_index = torch.full((len(node_ids), len(node_ids)), -1, dtype=torch.long)
    for src_idx, source in enumerate(node_ids):
        source_type = node_types.get(source, "unknown")
        for dst_idx, target in enumerate(node_ids):
            if src_idx == dst_idx:
                continue
            target_type = node_types.get(target, "unknown")
            relation = RELATION_BY_TYPE_PAIR.get((source_type, target_type))
            if relation is None:
                continue
            relation_index[src_idx, dst_idx] = relation_to_idx[relation]
    return relation_index


def build_feature_matrix(
    graph: dict,
    rows: list[dict],
    node_ids: list[str],
    node_index: dict[str, int],
    support: torch.Tensor,
) -> torch.Tensor:
    node_meta = {node["id"]: node for node in graph.get("nodes", [])}
    edge_touch_counts = {node_id: 0.0 for node_id in node_ids}
    for edge in graph.get("edges", []):
        source = edge.get("source")
        target = edge.get("target")
        if source in edge_touch_counts:
            edge_touch_counts[source] += float(edge.get("weight", 1.0))
        if target in edge_touch_counts:
            edge_touch_counts[target] += float(edge.get("weight", 1.0))

    per_node = {
        node_id: {
            "role_counts": {key: 0.0 for key in ROLE_FIELDS.values()},
            "numeric_sums": {key: 0.0 for key in NUMERIC_FIELDS},
            "numeric_counts": {key: 0.0 for key in NUMERIC_FIELDS},
            "conflict_counts": {key: 0.0 for key in CONFLICT_TYPES},
        }
        for node_id in node_ids
    }

    for row in rows:
        conflict_type = normalize_conflict_type(row.get("conflict_type"))
        active_ids = []
        for field, role_name in ROLE_FIELDS.items():
            raw_value = (row.get(field) or "").strip()
            if not raw_value:
                continue
            if field == "source_agent":
                node_id = qualified_node_id("agent", raw_value)
            elif field == "target_agent":
                node_id = qualified_node_id(target_node_type(raw_value), raw_value)
            elif field == "parameter":
                node_id = qualified_node_id("parameter", raw_value)
            elif field == "affected_service":
                node_id = qualified_node_id("service", raw_value)
            elif field == "affected_kpi":
                node_id = qualified_node_id("kpi", raw_value)
            elif field == "mitigation_action":
                node_id = qualified_node_id("mitigation", raw_value)
            elif field == "latest_energy_command":
                node_id = qualified_node_id("mitigation", raw_value)
            else:
                node_id = raw_value
            if node_id not in per_node:
                continue
            per_node[node_id]["role_counts"][role_name] += 1.0
            active_ids.append(node_id)
        for node_id in set(active_ids):
            per_node[node_id]["conflict_counts"][conflict_type] += 1.0
            for numeric_field in NUMERIC_FIELDS:
                value = safe_float(row.get(numeric_field))
                per_node[node_id]["numeric_sums"][numeric_field] += value
                per_node[node_id]["numeric_counts"][numeric_field] += 1.0

    feature_rows = []
    support_degree = support.sum(dim=1)
    total_support = float(max(rows and len(rows) or 1, 1))

    for node_id in node_ids:
        node = node_meta.get(node_id, {})
        node_type = node.get("type", "unknown")
        type_vector = [1.0 if node_type == expected else 0.0 for expected in NODE_TYPES]
        stats = per_node[node_id]
        role_features = [math.log1p(stats["role_counts"][key]) for key in ROLE_FIELDS.values()]
        numeric_features = []
        for numeric_field in NUMERIC_FIELDS:
            count = stats["numeric_counts"][numeric_field]
            mean_value = stats["numeric_sums"][numeric_field] / count if count else 0.0
            numeric_features.append(mean_value)
        conflict_total = sum(stats["conflict_counts"].values()) or 1.0
        conflict_features = [stats["conflict_counts"][key] / conflict_total for key in CONFLICT_TYPES]
        feature_rows.append(
            type_vector
            + [
                math.log1p(float(node.get("event_count", 0.0))),
                math.log1p(edge_touch_counts[node_id]),
                math.log1p(float(support_degree[node_index[node_id]].item())),
                float(support_degree[node_index[node_id]].item()) / total_support,
            ]
            + role_features
            + numeric_features
            + conflict_features
        )

    return torch.tensor(feature_rows, dtype=torch.float32)


def normalize_features(
    features: torch.Tensor,
    *,
    mean: torch.Tensor | None = None,
    std: torch.Tensor | None = None,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    if mean is None:
        mean = features.mean(dim=0, keepdim=True)
    if std is None:
        std = features.std(dim=0, keepdim=True)
    std = torch.where(std < 1e-6, torch.ones_like(std), std)
    return (features - mean) / std, mean, std


def tensors_from_rows(graph: dict, rows: list[dict]) -> tuple[dict, list[dict], list[str], torch.Tensor, torch.Tensor, torch.Tensor]:
    node_ids = [node["id"] for node in graph.get("nodes", [])]
    node_index = {node_id: idx for idx, node_id in enumerate(node_ids)}
    support = build_support_matrix(rows, node_index)
    raw_features = build_feature_matrix(graph, rows, node_ids, node_index, support)
    features, _, _ = normalize_features(raw_features)
    target = build_target_adjacency(graph, node_ids, node_index)
    return graph, rows, node_ids, features, support, target


def load_case_tensors(case: TrainingCase) -> tuple[dict, list[dict], list[str], torch.Tensor, torch.Tensor, torch.Tensor]:
    graph = load_json(case.graph_path)
    rows = read_csv_rows(case.dataset_path)
    return tensors_from_rows(graph, rows)


def rows_for_subset_by_round(case: TrainingCase) -> tuple[list[dict], list[int]]:
    round_summary_path = case.scenario_dir / "round_summary.csv"
    if not round_summary_path.exists():
        raise FileNotFoundError(f"round summary not found for scenario {case.scenario}: {round_summary_path}")

    round_rows = read_round_summary(round_summary_path)
    subset_rows: list[dict] = []
    contributing_rounds: list[int] = []
    remaining = case.subset_size
    for round_entry in round_rows:
        if remaining <= 0:
            break
        round_dataset_path = Path(round_entry["dataset_path"])
        if not round_dataset_path.exists():
            continue
        rows = read_csv_rows(round_dataset_path)
        if not rows:
            continue
        take = min(remaining, len(rows))
        subset_rows.extend(rows[:take])
        contributing_rounds.append(int(round_entry["round"]))
        remaining -= take

    if len(subset_rows) != case.subset_size:
        raise SystemExit(
            f"unable to reconstruct subset rows by rounds for {case.scenario} subset {case.subset_size}: "
            f"expected {case.subset_size}, got {len(subset_rows)}"
        )
    return subset_rows, contributing_rounds


def subset_rows_with_boundaries(case: TrainingCase) -> tuple[list[dict], list[int], list[tuple[int, int, int]]]:
    round_summary = read_round_summary(case.scenario_dir / "round_summary.csv")
    subset_rows: list[dict] = []
    contributing_rounds: list[int] = []
    boundaries: list[tuple[int, int, int]] = []
    remaining = case.subset_size
    offset = 0
    for round_entry in round_summary:
        if remaining <= 0:
            break
        round_dataset_path = Path(round_entry["dataset_path"])
        if not round_dataset_path.exists():
            continue
        rows = read_csv_rows(round_dataset_path)
        if not rows:
            continue
        take = min(remaining, len(rows))
        subset_rows.extend(rows[:take])
        round_number = int(round_entry["round"])
        contributing_rounds.append(round_number)
        boundaries.append((round_number, offset, offset + take))
        offset += take
        remaining -= take
    if len(subset_rows) != case.subset_size:
        raise SystemExit(
            f"unable to reconstruct subset rows by rounds for {case.scenario} subset {case.subset_size}: "
            f"expected {case.subset_size}, got {len(subset_rows)}"
        )
    return subset_rows, contributing_rounds, boundaries


def build_round_split(
    case: TrainingCase,
    test_round_fraction: float,
    min_test_rounds: int,
) -> RoundSplit:
    try:
        subset_rows, contributing_rounds, round_boundaries = subset_rows_with_boundaries(case)
    except SystemExit:
        rows = read_csv_rows(case.dataset_path)
        fallback = build_direct_row_split(
            rows,
            test_fraction=max(float(test_round_fraction), 0.25),
            min_test_rows=1,
        )
        return RoundSplit(
            mode="direct_row_fallback_from_incomplete_round_index",
            train_rows=fallback.train_rows,
            test_rows=fallback.test_rows,
            train_rounds=[],
            test_rounds=[],
            contributing_rounds=[],
        )
    if len(contributing_rounds) < 2:
        fallback = build_direct_row_split(
            subset_rows,
            test_fraction=max(float(test_round_fraction), 0.25),
            min_test_rows=1,
        )
        return RoundSplit(
            mode="direct_row_fallback_from_round_holdout",
            train_rows=fallback.train_rows,
            test_rows=fallback.test_rows,
            train_rounds=[],
            test_rounds=[],
            contributing_rounds=contributing_rounds,
        )

    requested_test_rounds = max(min_test_rounds, int(math.ceil(len(contributing_rounds) * test_round_fraction)))
    num_test_rounds = min(len(contributing_rounds) - 1, requested_test_rounds)
    train_rounds = contributing_rounds[:-num_test_rounds]
    test_rounds = contributing_rounds[-num_test_rounds:]
    train_rows: list[dict[str, Any]] = []
    test_rows: list[dict[str, Any]] = []

    for round_number, start, end in round_boundaries:
        rows = subset_rows[start:end]
        if round_number in train_rounds:
            train_rows.extend(rows)
        elif round_number in test_rounds:
            test_rows.extend(rows)

    if not train_rows or not test_rows:
        raise SystemExit(
            f"round-based split produced an empty partition for {case.scenario} subset {case.subset_size}: "
            f"train_rounds={train_rounds}, test_rounds={test_rounds}"
        )

    return RoundSplit(
        mode="round_holdout",
        train_rows=train_rows,
        test_rows=test_rows,
        train_rounds=train_rounds,
        test_rounds=test_rounds,
        contributing_rounds=contributing_rounds,
    )


def build_manual_round_split(
    case: TrainingCase,
    train_rounds: list[int],
    test_rounds: list[int],
) -> RoundSplit:
    subset_rows, contributing_rounds, round_boundaries = subset_rows_with_boundaries(case)
    contributing_set = set(contributing_rounds)
    train_set = set(train_rounds)
    test_set = set(test_rounds)

    unknown = sorted((train_set | test_set) - contributing_set)
    if unknown:
        raise SystemExit(
            f"manual round split for {case.scenario} subset {case.subset_size} references rounds not present "
            f"in the subset: {unknown}; contributing rounds are {contributing_rounds}"
        )
    if not train_set or not test_set:
        raise SystemExit("manual round split requires non-empty --train-rounds and --test-rounds")
    if train_set & test_set:
        raise SystemExit(f"manual round split has overlapping train/test rounds: {sorted(train_set & test_set)}")

    selected = train_set | test_set
    train_rows: list[dict[str, Any]] = []
    test_rows: list[dict[str, Any]] = []
    selected_rounds: list[int] = []
    for round_number, start, end in round_boundaries:
        if round_number not in selected:
            continue
        selected_rounds.append(round_number)
        rows = subset_rows[start:end]
        if round_number in train_set:
            train_rows.extend(rows)
        elif round_number in test_set:
            test_rows.extend(rows)

    if not train_rows or not test_rows:
        raise SystemExit(
            f"manual round split produced an empty partition for {case.scenario} subset {case.subset_size}: "
            f"train_rounds={sorted(train_set)}, test_rounds={sorted(test_set)}"
        )

    return RoundSplit(
        mode="manual_round_split",
        train_rows=train_rows,
        test_rows=test_rows,
        train_rounds=sorted(train_set),
        test_rounds=sorted(test_set),
        contributing_rounds=selected_rounds,
    )


def build_direct_row_split(
    rows: list[dict],
    test_fraction: float,
    min_test_rows: int,
) -> RoundSplit:
    if len(rows) < 2:
        raise SystemExit("direct dataset split requires at least 2 rows")
    if not (0.0 < float(test_fraction) < 1.0):
        raise SystemExit("--direct-test-fraction must be between 0 and 1")

    requested_test_rows = max(int(math.ceil(len(rows) * float(test_fraction))), int(min_test_rows))
    num_test_rows = min(len(rows) - 1, requested_test_rows)
    split_at = len(rows) - num_test_rows
    train_rows = rows[:split_at]
    test_rows = rows[split_at:]

    if not train_rows or not test_rows:
        raise SystemExit(
            f"direct dataset split produced an empty partition: train_rows={len(train_rows)}, test_rows={len(test_rows)}"
        )

    return RoundSplit(
        mode="direct_row_holdout",
        train_rows=train_rows,
        test_rows=test_rows,
        train_rounds=[],
        test_rounds=[],
        contributing_rounds=[],
    )


class DenseGraphSAGELayer(nn.Module):
    def __init__(self, in_dim: int, out_dim: int) -> None:
        super().__init__()
        self.self_linear = nn.Linear(in_dim, out_dim)
        self.neigh_linear = nn.Linear(in_dim, out_dim)

    def forward(self, x: torch.Tensor, support: torch.Tensor) -> torch.Tensor:
        degree = support.sum(dim=1, keepdim=True).clamp(min=1.0)
        neigh = support @ x / degree
        return self.self_linear(x) + self.neigh_linear(neigh)


class GraphSAGEReconstructor(nn.Module):
    def __init__(self, in_dim: int, hidden_dim: int, embed_dim: int, dropout: float) -> None:
        super().__init__()
        self.sage1 = DenseGraphSAGELayer(in_dim, hidden_dim)
        self.sage2 = DenseGraphSAGELayer(hidden_dim, embed_dim)
        self.dropout = dropout
        decoder_dim = embed_dim * 4
        self.relation_decoders = nn.ModuleList(
            [
                nn.Sequential(
                    nn.Linear(decoder_dim, hidden_dim),
                    nn.ReLU(),
                    nn.Dropout(dropout),
                    nn.Linear(hidden_dim, 1),
                )
                for _ in RELATION_TYPES
            ]
        )

    def encode(self, x: torch.Tensor, support: torch.Tensor) -> torch.Tensor:
        hidden = self.sage1(x, support)
        hidden = F.relu(hidden)
        hidden = F.dropout(hidden, p=self.dropout, training=self.training)
        embedding = self.sage2(hidden, support)
        return F.normalize(embedding, p=2, dim=1)

    def decode(self, embedding: torch.Tensor, relation_index: torch.Tensor) -> torch.Tensor:
        n_nodes = embedding.shape[0]
        src = embedding.unsqueeze(1).expand(n_nodes, n_nodes, -1)
        dst = embedding.unsqueeze(0).expand(n_nodes, n_nodes, -1)
        pair_features = torch.cat([src, dst, torch.abs(src - dst), src * dst], dim=-1)
        logits = torch.full(
            (n_nodes, n_nodes),
            -20.0,
            dtype=pair_features.dtype,
            device=pair_features.device,
        )
        for relation_idx, decoder in enumerate(self.relation_decoders):
            relation_mask = relation_index == relation_idx
            if not relation_mask.any():
                continue
            relation_logits = decoder(pair_features[relation_mask]).squeeze(-1)
            logits[relation_mask] = relation_logits
        return logits

    def forward(
        self,
        x: torch.Tensor,
        support: torch.Tensor,
        relation_index: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        embedding = self.encode(x, support)
        return embedding, self.decode(embedding, relation_index)


def compute_metrics(
    logits: torch.Tensor,
    target: torch.Tensor,
    threshold: float,
    pair_mask: torch.Tensor | None = None,
) -> dict:
    mask = ~torch.eye(target.shape[0], dtype=torch.bool, device=target.device)
    if pair_mask is not None:
        mask = mask & pair_mask.to(device=target.device, dtype=torch.bool)
    probs = torch.sigmoid(logits)
    pred = (probs >= threshold).float()
    target_masked = target[mask]
    pred_masked = pred[mask]

    tp = int(((pred_masked == 1) & (target_masked == 1)).sum().item())
    fp = int(((pred_masked == 1) & (target_masked == 0)).sum().item())
    fn = int(((pred_masked == 0) & (target_masked == 1)).sum().item())
    tn = int(((pred_masked == 0) & (target_masked == 0)).sum().item())
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = (2.0 * precision * recall / (precision + recall)) if (precision + recall) else 0.0

    return {
        "threshold": threshold,
        "tp": tp,
        "fp": fp,
        "fn": fn,
        "tn": tn,
        "precision": round(precision, 6),
        "recall": round(recall, 6),
        "f1": round(f1, 6),
        "predicted_edges": int(pred_masked.sum().item()),
        "target_edges": int(target_masked.sum().item()),
    }


def top_edges(
    logits: torch.Tensor,
    node_ids: list[str],
    target_graph: dict,
    threshold: float,
    pair_mask: torch.Tensor | None = None,
) -> list[dict]:
    truth = {
        (edge.get("source"), edge.get("target")): edge.get("relation", "unknown")
        for edge in target_graph.get("edges", [])
    }
    probs = torch.sigmoid(logits).detach().cpu()
    edges = []
    for src_idx, source in enumerate(node_ids):
        for dst_idx, target in enumerate(node_ids):
            if src_idx == dst_idx:
                continue
            if pair_mask is not None and not bool(pair_mask[src_idx, dst_idx].item()):
                continue
            score = float(probs[src_idx, dst_idx].item())
            if score < threshold:
                continue
            edges.append(
                {
                    "source": source,
                    "target": target,
                    "score": round(score, 6),
                    "baseline_relation": truth.get((source, target)),
                    "is_true_edge": (source, target) in truth,
                }
            )
    edges.sort(key=lambda item: (-item["score"], item["source"], item["target"]))
    return edges


def train_case(
    case: TrainingCase,
    direct_mode: bool,
    epochs: tuple[int, ...],
    hidden_dim: int,
    embed_dim: int,
    dropout: float,
    learning_rate: float,
    weight_decay: float,
    threshold: float,
    loss_mask_mode: str,
    negative_edge_weight: float,
    pos_weight_scale: float,
    max_pos_weight: float,
    fp_penalty_weight: float,
    fp_penalty_margin: float,
    selection_mode: str,
    selection_fp_weight: float,
    selection_precision_weight: float,
    pair_mask_mode: str,
    domain_scope: str,
    domain_scope_mode: str,
    seed: int,
    split_by_rounds: bool,
    test_round_fraction: float,
    min_test_rounds: int,
    manual_train_rounds: list[int] | None,
    manual_test_rounds: list[int] | None,
    direct_test_fraction: float,
    direct_min_test_rows: int,
    init_model_path: Path | None,
) -> dict:
    set_seed(seed)
    ensure_dir(case.output_dir)

    split = None
    if manual_train_rounds or manual_test_rounds:
        if not (manual_train_rounds and manual_test_rounds):
            raise SystemExit("manual round split requires both --train-rounds and --test-rounds")
        split = build_manual_round_split(case, manual_train_rounds, manual_test_rounds)
    elif split_by_rounds:
        split = build_round_split(case, test_round_fraction, min_test_rounds)
    elif direct_mode:
        if direct_test_fraction > 0:
            split = build_direct_row_split(read_csv_rows(case.dataset_path), direct_test_fraction, direct_min_test_rows)

    if split is not None:
        rows = split.train_rows + split.test_rows
        combined_graph = build_graph_from_rows(rows)
        train_graph = build_graph_from_rows(split.train_rows)
        eval_graph = build_graph_from_rows(split.test_rows)
        node_ids = [node["id"] for node in combined_graph.get("nodes", [])]
        node_index = {node_id: idx for idx, node_id in enumerate(node_ids)}
        train_support = build_support_matrix(split.train_rows, node_index)
        test_support = build_support_matrix(split.test_rows, node_index)
        train_raw = build_feature_matrix(train_graph, split.train_rows, node_ids, node_index, train_support)
        train_features, feature_mean, feature_std = normalize_features(train_raw)
        test_raw = build_feature_matrix(eval_graph, split.test_rows, node_ids, node_index, test_support)
        test_features, _, _ = normalize_features(test_raw, mean=feature_mean, std=feature_std)
        train_target = build_target_adjacency(train_graph, node_ids, node_index)
        eval_target = build_target_adjacency(eval_graph, node_ids, node_index)
        train_rows = split.train_rows
        test_rows = split.test_rows
    else:
        rows = read_csv_rows(case.dataset_path)
        graph = build_graph_from_rows(rows)
        _, rows, node_ids, train_features, train_support, train_target = tensors_from_rows(graph, rows)
        train_rows = rows
        test_rows = []
        test_features = None
        test_support = None
        eval_target = train_target
        eval_graph = graph

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    train_features = train_features.to(device)
    train_support = train_support.to(device)
    train_target = train_target.to(device)
    eval_target = eval_target.to(device)
    if test_features is not None and test_support is not None:
        test_features = test_features.to(device)
        test_support = test_support.to(device)

    model = GraphSAGEReconstructor(
        in_dim=train_features.shape[1],
        hidden_dim=hidden_dim,
        embed_dim=embed_dim,
        dropout=dropout,
    ).to(device)
    if init_model_path is not None:
        checkpoint = torch.load(init_model_path, map_location=device)
        state_dict = checkpoint.get("state_dict", checkpoint)
        model.load_state_dict(state_dict)
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=learning_rate,
        weight_decay=weight_decay,
    )

    max_epoch = max(epochs)
    if split is not None:
        mask_graph = combined_graph
    else:
        mask_graph = graph
    valid_pair_mask = build_valid_pair_mask(mask_graph, node_ids).to(device)
    resolved_domain_scope_mode = resolve_domain_scope_mode(domain_scope, domain_scope_mode)
    domain_pair_mask = build_domain_pair_mask(
        mask_graph,
        rows,
        node_ids,
        domain_scope,
        resolved_domain_scope_mode,
    ).to(device)
    relation_index = build_relation_index_matrix(mask_graph, node_ids).to(device)
    train_mask = ~torch.eye(train_target.shape[0], dtype=torch.bool, device=device)
    if pair_mask_mode == "valid_types":
        train_mask = train_mask & valid_pair_mask
    if domain_scope != "mixed":
        train_mask = train_mask & domain_pair_mask
        if int(domain_pair_mask.sum().item()) == 0:
            raise SystemExit(
                f"domain scope '{domain_scope}' with mode '{resolved_domain_scope_mode}' produced zero candidate pairs. "
                "The selected dataset does not appear to contain compatible domain rows."
            )
    if loss_mask_mode == "support":
        loss_mask = train_mask & ((train_support > 0) | (train_target > 0))
    else:
        loss_mask = train_mask
    if int(loss_mask.sum().item()) == 0:
        raise SystemExit(
            f"training mask is empty for domain scope '{domain_scope}' ({resolved_domain_scope_mode}). "
            "No valid supervised pairs remain after applying the current masks."
        )
    positives = float(train_target[loss_mask].sum().item())
    negatives = float(loss_mask.sum().item() - positives)
    raw_pos_weight = negatives / max(positives, 1.0)
    effective_pos_weight = raw_pos_weight * max(pos_weight_scale, 0.0)
    if max_pos_weight > 0.0:
        effective_pos_weight = min(effective_pos_weight, max_pos_weight)
    pos_weight = torch.tensor([effective_pos_weight], dtype=torch.float32, device=device)
    negative_mask = loss_mask & (train_target < 0.5)

    checkpoints = set(epochs)
    history = []
    best = None
    best_score = float("-inf")
    started_at = time.time()
    checkpoint_dir = case.output_dir / "checkpoints"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    for epoch in range(1, max_epoch + 1):
        model.train()
        optimizer.zero_grad()
        _, train_logits = model(train_features, train_support, relation_index)
        loss_terms = F.binary_cross_entropy_with_logits(
            train_logits[loss_mask],
            train_target[loss_mask],
            reduction="none",
            pos_weight=pos_weight,
        )
        if negative_edge_weight != 1.0:
            negative_targets = train_target[loss_mask] < 0.5
            loss_terms = torch.where(negative_targets, loss_terms * negative_edge_weight, loss_terms)
        loss = loss_terms.mean()
        if fp_penalty_weight > 0.0 and negative_mask.any():
            negative_probs = torch.sigmoid(train_logits[negative_mask])
            fp_penalty = torch.relu(negative_probs - fp_penalty_margin).mean()
            loss = loss + fp_penalty_weight * fp_penalty
        loss.backward()
        optimizer.step()

        if epoch not in checkpoints:
            continue

        model.eval()
        with torch.no_grad():
            train_embedding, train_logits = model(train_features, train_support, relation_index)
            train_metrics = compute_metrics(
                train_logits,
                train_target,
                threshold,
                pair_mask=train_mask,
            )
            eval_embedding = train_embedding
            eval_logits = train_logits
            eval_metrics = train_metrics
            if test_features is not None and test_support is not None:
                eval_embedding, eval_logits = model(test_features, test_support, relation_index)
                eval_metrics = compute_metrics(
                    eval_logits,
                    eval_target,
                    threshold,
                    pair_mask=train_mask,
                )
            snapshot = {
                "epoch": epoch,
                "loss": round(float(loss.item()), 6),
                **eval_metrics,
                "train_precision": train_metrics["precision"],
                "train_recall": train_metrics["recall"],
                "train_f1": train_metrics["f1"],
                "train_tp": train_metrics["tp"],
                "train_fp": train_metrics["fp"],
                "train_fn": train_metrics["fn"],
                "train_tn": train_metrics["tn"],
            }
            history.append(snapshot)
            torch.save(
                {
                    "state_dict": model.state_dict(),
                    "node_ids": node_ids,
                    "feature_dim": int(train_features.shape[1]),
                    "hidden_dim": hidden_dim,
                    "embed_dim": embed_dim,
                    "dropout": dropout,
                    "threshold": threshold,
                    "epoch": epoch,
                },
                checkpoint_dir / f"epoch_{epoch}.pt",
            )
            if selection_mode == "fp_penalized":
                fp_total = eval_metrics["fp"] + eval_metrics["tn"]
                fp_rate = (eval_metrics["fp"] / fp_total) if fp_total else 0.0
                score = (
                    eval_metrics["f1"]
                    + selection_precision_weight * eval_metrics["precision"]
                    - selection_fp_weight * fp_rate
                )
            else:
                score = eval_metrics["f1"]
            if score >= best_score:
                best_score = score
                best = {
                    "score": round(float(score), 6),
                    "epoch": epoch,
                    "metrics": eval_metrics,
                    "train_metrics": train_metrics,
                    "embedding": eval_embedding.detach().cpu(),
                    "logits": eval_logits.detach().cpu(),
                }

    best_edges = top_edges(
        best["logits"],
        node_ids,
        eval_graph,
        threshold,
        pair_mask=train_mask.cpu(),
    ) if best else []
    torch.save(
        {
            "state_dict": model.state_dict(),
            "node_ids": node_ids,
            "feature_dim": int(train_features.shape[1]),
            "hidden_dim": hidden_dim,
            "embed_dim": embed_dim,
            "dropout": dropout,
            "threshold": threshold,
            "best_epoch": best["epoch"] if best else None,
        },
        case.output_dir / "best_model.pt",
    )

    summary = {
        "scenario": case.scenario,
        "subset_size": case.subset_size,
        "dataset_path": str(case.dataset_path),
        "graph_path": str(case.graph_path),
        "output_dir": str(case.output_dir),
        "init_model": str(init_model_path) if init_model_path else "",
        "loss_mask_mode": loss_mask_mode,
        "negative_edge_weight": negative_edge_weight,
        "pos_weight_scale": pos_weight_scale,
        "max_pos_weight": max_pos_weight,
        "effective_pos_weight": round(float(effective_pos_weight), 6),
        "fp_penalty_weight": fp_penalty_weight,
        "fp_penalty_margin": fp_penalty_margin,
        "selection_mode": selection_mode,
        "selection_fp_weight": selection_fp_weight,
        "selection_precision_weight": selection_precision_weight,
        "pair_mask_mode": pair_mask_mode,
        "domain_scope": domain_scope,
        "domain_scope_mode": resolved_domain_scope_mode,
        "device": str(device),
        "rows": len(rows),
        "train_rows": len(train_rows),
        "test_rows": len(test_rows),
        "nodes": len(node_ids),
        "candidate_pairs": int(train_mask.sum().item()),
        "domain_candidate_pairs": int(domain_pair_mask.sum().item()) if domain_scope != "mixed" else 0,
        "target_edges": int(eval_target.sum().item()),
        "train_target_edges": int(train_target.sum().item()),
        "eval_target_edges": int(eval_target.sum().item()),
        "feature_dim": int(train_features.shape[1]),
        "epochs_requested": list(epochs),
        "elapsed_seconds": round(time.time() - started_at, 3),
        "split_mode": split.mode if split else "none",
        "train_rounds": split.train_rounds if split else [],
        "test_rounds": split.test_rounds if split else [],
        "contributing_rounds": split.contributing_rounds if split else [],
        "best_epoch": best["epoch"] if best else None,
        "best_score": best.get("score") if best else None,
        "best_metrics": best["metrics"] if best else {},
        "train_metrics_at_best": best["train_metrics"] if best else {},
        "history": history,
        "predicted_edges_at_best": best_edges[:50],
    }
    with (case.output_dir / "training_summary.json").open("w") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)

    with (case.output_dir / "history.csv").open("w", newline="") as f:
        fieldnames = [
            "epoch",
            "loss",
            "precision",
            "recall",
            "f1",
            "tp",
            "fp",
            "fn",
            "tn",
            "predicted_edges",
            "target_edges",
            "threshold",
            "train_precision",
            "train_recall",
            "train_f1",
            "train_tp",
            "train_fp",
            "train_fn",
            "train_tn",
        ]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(history)

    return summary


def main() -> int:
    args = parse_args()
    epochs = parse_int_tuple(args.epochs)
    subset_sizes = parse_int_tuple(args.subset_sizes)
    manual_train_rounds = parse_round_list(args.train_rounds) if args.train_rounds else None
    manual_test_rounds = parse_round_list(args.test_rounds) if args.test_rounds else None
    if (manual_train_rounds is None) != (manual_test_rounds is None):
        raise SystemExit("use both --train-rounds and --test-rounds together")

    direct_mode = bool(args.dataset_path or args.graph_path)
    if direct_mode and not (args.dataset_path and args.graph_path):
        raise SystemExit("use both --dataset-path and --graph-path together")
    if direct_mode and (args.split_by_rounds or manual_train_rounds or manual_test_rounds):
        raise SystemExit("round-based splits are not supported in direct dataset mode; use --direct-test-fraction")

    if direct_mode:
        dataset_path = Path(args.dataset_path)
        graph_path = Path(args.graph_path)
        output_root = Path(args.output_dir) if args.output_dir else dataset_path.parent / DEFAULT_OUTPUT_STEM
        ensure_dir(output_root)
        experiment_dir = dataset_path.parent
        cases = build_direct_case(dataset_path, graph_path, args.scenario_label, output_root)
    else:
        experiment_dir = Path(args.experiment_dir) if args.experiment_dir else latest_experiment_dir(DEFAULT_EXPERIMENT_ROOT)
        output_root = Path(args.output_dir) if args.output_dir else experiment_dir / DEFAULT_OUTPUT_STEM
        ensure_dir(output_root)
        reports = selected_reports(experiment_dir, args.scenarios)
        cases = build_cases(experiment_dir, reports, subset_sizes, output_root)

    aggregate = {
        "generated_at": int(time.time()),
        "generated_at_iso": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "experiment_dir": str(experiment_dir),
        "output_root": str(output_root),
        "epochs": list(epochs),
        "subset_sizes": [] if direct_mode else list(subset_sizes),
        "threshold": args.threshold,
        "loss_mask_mode": args.loss_mask_mode,
        "negative_edge_weight": args.negative_edge_weight,
        "pos_weight_scale": args.pos_weight_scale,
        "max_pos_weight": args.max_pos_weight,
        "fp_penalty_weight": args.fp_penalty_weight,
        "fp_penalty_margin": args.fp_penalty_margin,
        "selection_mode": args.selection_mode,
        "selection_fp_weight": args.selection_fp_weight,
        "selection_precision_weight": args.selection_precision_weight,
        "pair_mask_mode": args.pair_mask_mode,
        "domain_scope": args.domain_scope,
        "domain_scope_mode": resolve_domain_scope_mode(args.domain_scope, args.domain_scope_mode),
        "direct_mode": direct_mode,
        "dataset_path": args.dataset_path or "",
        "graph_path": args.graph_path or "",
        "scenario_label": args.scenario_label if direct_mode else "",
        "split_by_rounds": args.split_by_rounds,
        "test_round_fraction": args.test_round_fraction,
        "min_test_rounds": args.min_test_rounds,
        "direct_test_fraction": args.direct_test_fraction,
        "direct_min_test_rows": args.direct_min_test_rows,
        "train_rounds": manual_train_rounds or [],
        "test_rounds": manual_test_rounds or [],
        "cases": [],
    }

    print(f"Experimento de treino: {experiment_dir}")
    print(f"Saída do GraphSAGE: {output_root}")
    print(f"Epochs: {', '.join(str(value) for value in epochs)}")
    if direct_mode:
        print(f"Dataset direto: {args.dataset_path}")
        print(f"Grafo direto: {args.graph_path}")
    else:
        print(f"Subsets: {', '.join(str(value) for value in subset_sizes)}")
    if manual_train_rounds and manual_test_rounds:
        print(f"Split manual de rodadas: treino={manual_train_rounds} | teste={manual_test_rounds}")
    elif direct_mode:
        print(f"Split direto temporal: {args.direct_test_fraction:.2f} para teste")
    else:
        print(f"Split por rodadas: {'sim' if args.split_by_rounds else 'não'}")

    for case in cases:
        print(f"\n=== {case.scenario} | subset {case.subset_size} ===")
        summary = train_case(
            case=case,
            direct_mode=direct_mode,
            epochs=epochs,
            hidden_dim=args.hidden_dim,
            embed_dim=args.embed_dim,
            dropout=args.dropout,
            learning_rate=args.learning_rate,
            weight_decay=args.weight_decay,
            threshold=args.threshold,
            loss_mask_mode=args.loss_mask_mode,
            negative_edge_weight=args.negative_edge_weight,
            pos_weight_scale=args.pos_weight_scale,
            max_pos_weight=args.max_pos_weight,
            fp_penalty_weight=args.fp_penalty_weight,
            fp_penalty_margin=args.fp_penalty_margin,
            selection_mode=args.selection_mode,
            selection_fp_weight=args.selection_fp_weight,
            selection_precision_weight=args.selection_precision_weight,
            pair_mask_mode=args.pair_mask_mode,
            domain_scope=args.domain_scope,
            domain_scope_mode=args.domain_scope_mode,
            seed=args.seed,
            split_by_rounds=args.split_by_rounds,
            test_round_fraction=args.test_round_fraction,
            min_test_rounds=args.min_test_rounds,
            manual_train_rounds=manual_train_rounds,
            manual_test_rounds=manual_test_rounds,
            direct_test_fraction=args.direct_test_fraction,
            direct_min_test_rows=args.direct_min_test_rows,
            init_model_path=Path(args.init_model) if args.init_model else None,
        )
        aggregate["cases"].append(summary)
        best = summary.get("best_metrics", {})
        if summary.get("test_rows", 0) > 0:
            train_best = summary.get("train_metrics_at_best", {})
            print(
                "best_epoch={best_epoch} | test_f1={test_f1:.4f} | test_precision={test_precision:.4f} | "
                "test_recall={test_recall:.4f} | train_f1={train_f1:.4f} | "
                "train_rounds={train_rounds} | test_rounds={test_rounds}".format(
                    best_epoch=summary.get("best_epoch"),
                    test_f1=best.get("f1", 0.0),
                    test_precision=best.get("precision", 0.0),
                    test_recall=best.get("recall", 0.0),
                    train_f1=train_best.get("f1", 0.0),
                    train_rounds=summary.get("train_rounds", []),
                    test_rounds=summary.get("test_rounds", []),
                )
            )
        else:
            print(
                "best_epoch={best_epoch} | f1={f1:.4f} | precision={precision:.4f} | "
                "recall={recall:.4f}".format(
                    best_epoch=summary.get("best_epoch"),
                    f1=best.get("f1", 0.0),
                    precision=best.get("precision", 0.0),
                    recall=best.get("recall", 0.0),
                )
            )

    aggregate_path = output_root / "aggregate_report.json"
    with aggregate_path.open("w") as f:
        json.dump(aggregate, f, indent=2, ensure_ascii=False)

    print(f"\nRelatório agregado: {aggregate_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
