#!/usr/bin/env python3
"""
Train a GraphSAGE-style graph reconstructor on completed conflitos datasets.

This script is the first practical step after the collection protocol:

- it consumes the `50`, `150`, and `450` conflict subsets generated by
  `scripts/run_experimentos_conflitos.py`;
- it builds node features from the exported conflict CSV;
- it builds a support graph from row-level node co-occurrence;
- it trains a GraphSAGE-style encoder plus a link predictor to reconstruct the
  scenario conflict graph;
- it reports reconstruction precision/recall/F1 across an epoch sweep.

The goal is to align the GreenRAN pipeline with the next methodological step of
`conflitos`: training a graph learner after the `50/150/450` datasets have been
collected.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import random
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import torch
import torch.nn as nn
import torch.nn.functional as F


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXPERIMENT_ROOT = PROJECT_ROOT / "runs" / "experimentos_conflitos"
DEFAULT_OUTPUT_STEM = "graphsage_training"
DEFAULT_EPOCHS = (50, 100, 200, 400, 600, 800, 1000)
DEFAULT_SUBSET_SIZES = (50, 150, 450)
NODE_TYPES = ("agent", "parameter", "kpi", "service", "mitigation", "arbiter", "unknown")
ROLE_FIELDS = {
    "source_agent": "source_agent",
    "target_agent": "target_agent",
    "parameter": "parameter",
    "affected_service": "service",
    "affected_kpi": "kpi",
    "mitigation_action": "mitigation",
    "latest_energy_command": "energy_command",
}
NUMERIC_FIELDS = (
    "observed_value",
    "threshold_value",
    "observed_delta_from_threshold",
    "cvar_ms",
    "p95_ms",
    "throughput_mbps",
    "global_packet_loss_percent",
    "latest_power_percent",
    "rapp_confidence",
    "ml_confidence",
)
CONFLICT_TYPES = ("direct", "indirect", "implicit", "unknown")


@dataclass
class TrainingCase:
    scenario: str
    subset_size: int
    dataset_path: Path
    graph_path: Path
    scenario_dir: Path
    output_dir: Path


@dataclass
class RoundSplit:
    mode: str
    train_rows: list[dict]
    test_rows: list[dict]
    train_rounds: list[int]
    test_rounds: list[int]
    contributing_rounds: list[int]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a GraphSAGE-style reconstructor on conflitos experiment outputs."
    )
    parser.add_argument(
        "--experiment-dir",
        help="completed experiment directory; defaults to the latest one under runs/experimentos_conflitos",
    )
    parser.add_argument(
        "--scenario",
        action="append",
        dest="scenarios",
        default=[],
        help="scenario slug to train; may be passed multiple times",
    )
    parser.add_argument(
        "--subset-sizes",
        default="50,150,450",
        help="comma-separated subset sizes to train",
    )
    parser.add_argument(
        "--epochs",
        default="50,100,200,400,600,800,1000",
        help="comma-separated epoch checkpoints; training runs until the maximum value",
    )
    parser.add_argument("--hidden-dim", type=int, default=16, help="hidden dimension for GraphSAGE")
    parser.add_argument("--embed-dim", type=int, default=16, help="embedding dimension for GraphSAGE")
    parser.add_argument("--dropout", type=float, default=0.10, help="dropout rate")
    parser.add_argument("--learning-rate", type=float, default=0.001, help="optimizer learning rate")
    parser.add_argument("--weight-decay", type=float, default=1e-4, help="optimizer weight decay")
    parser.add_argument("--threshold", type=float, default=0.5, help="edge threshold for reconstruction")
    parser.add_argument("--seed", type=int, default=42, help="random seed")
    parser.add_argument(
        "--split-by-rounds",
        action="store_true",
        help="train on the first rounds that compose each subset and evaluate on held-out final rounds",
    )
    parser.add_argument(
        "--test-round-fraction",
        type=float,
        default=0.30,
        help="fraction of contributing rounds reserved for evaluation when --split-by-rounds is enabled",
    )
    parser.add_argument(
        "--min-test-rounds",
        type=int,
        default=1,
        help="minimum number of held-out rounds when --split-by-rounds is enabled",
    )
    parser.add_argument(
        "--train-rounds",
        help="manual train rounds as comma-separated values/ranges, for example 1-34,35",
    )
    parser.add_argument(
        "--test-rounds",
        help="manual test rounds as comma-separated values/ranges, for example 36-38",
    )
    parser.add_argument(
        "--output-dir",
        help="directory where training artifacts will be written; defaults to <experiment>/graphsage_training",
    )
    return parser.parse_args()


def latest_experiment_dir(root: Path) -> Path:
    candidates = sorted(root.glob("*/experiment_report.json"))
    if not candidates:
        raise FileNotFoundError(f"no completed experiment_report.json found under {root}")
    return candidates[-1].parent


def load_json(path: Path) -> dict:
    with path.open() as f:
        return json.load(f)


def read_csv_rows(path: Path) -> list[dict]:
    with path.open() as f:
        return list(csv.DictReader(f))


def read_round_summary(path: Path) -> list[dict]:
    with path.open() as f:
        rows = list(csv.DictReader(f))
    for row in rows:
        row["round"] = int(row["round"])
        row["rows"] = int(row["rows"])
        row["cumulative_rows"] = int(row.get("cumulative_rows", 0) or 0)
    return rows


def safe_float(value: str | None) -> float:
    try:
        if value in (None, ""):
            return 0.0
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def normalize_conflict_type(value: str | None) -> str:
    text = (value or "").strip().lower()
    if text in {"direct", "indirect", "implicit"}:
        return text
    return "unknown"


def parse_int_tuple(raw: str) -> tuple[int, ...]:
    return tuple(sorted({int(piece.strip()) for piece in raw.split(",") if piece.strip()}))


def parse_round_list(raw: str) -> list[int]:
    values = set()
    for piece in raw.split(","):
        token = piece.strip()
        if not token:
            continue
        if "-" in token:
            start_text, end_text = token.split("-", 1)
            start = int(start_text.strip())
            end = int(end_text.strip())
            if end < start:
                raise SystemExit(f"invalid round range '{token}'")
            values.update(range(start, end + 1))
        else:
            values.add(int(token))
    return sorted(values)


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def set_seed(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def selected_reports(experiment_dir: Path, slugs: list[str]) -> list[dict]:
    report = load_json(experiment_dir / "experiment_report.json")
    scenario_reports = report.get("scenario_reports", [])
    if not slugs:
        return scenario_reports

    selected = []
    known = {entry["scenario"] for entry in scenario_reports}
    for slug in slugs:
        if slug not in known:
            raise SystemExit(f"scenario '{slug}' not found in {experiment_dir}")
        selected.extend(entry for entry in scenario_reports if entry["scenario"] == slug)
    return selected


def build_cases(
    experiment_dir: Path,
    scenario_reports: list[dict],
    subset_sizes: tuple[int, ...],
    output_root: Path,
) -> list[TrainingCase]:
    cases = []
    for report in scenario_reports:
        graph_path = Path(report["full_export"]["graph_path"])
        subset_map = {entry["requested_rows"]: entry for entry in report.get("subsets", [])}
        for subset_size in subset_sizes:
            subset = subset_map.get(subset_size)
            if subset is None:
                continue
            dataset_path = Path(subset["dataset_path"])
            output_dir = output_root / report["scenario"] / f"subset_{subset_size}"
            cases.append(
                TrainingCase(
                    scenario=report["scenario"],
                    subset_size=subset_size,
                    dataset_path=dataset_path,
                    graph_path=graph_path,
                    scenario_dir=experiment_dir / report["scenario"],
                    output_dir=output_dir,
                )
            )
    if not cases:
        raise SystemExit("no training cases found for the requested scenarios/subsets")
    return cases


def build_target_adjacency(graph: dict, node_ids: list[str], node_index: dict[str, int]) -> torch.Tensor:
    target = torch.zeros((len(node_ids), len(node_ids)), dtype=torch.float32)
    for edge in graph.get("edges", []):
        source = edge.get("source")
        target_node = edge.get("target")
        if source not in node_index or target_node not in node_index:
            continue
        target[node_index[source], node_index[target_node]] = 1.0
    return target


def build_conflict_type_target_adjacency(
    graph: dict,
    node_ids: list[str],
    node_index: dict[str, int],
    conflict_type: str,
    min_support: int = 1,
) -> torch.Tensor:
    target = torch.zeros((len(node_ids), len(node_ids)), dtype=torch.float32)
    for edge in graph.get("edges", []):
        source = edge.get("source")
        target_node = edge.get("target")
        conflict_types = edge.get("conflict_types", {}) or {}
        if source not in node_index or target_node not in node_index:
            continue
        support = conflict_types.get(conflict_type)
        if support is None:
            continue
        if safe_float(support) < float(min_support):
            continue
        if conflict_type in conflict_types:
            target[node_index[source], node_index[target_node]] = 1.0
    return target


def build_support_matrix(rows: list[dict], node_index: dict[str, int]) -> torch.Tensor:
    support = torch.zeros((len(node_index), len(node_index)), dtype=torch.float32)
    for row in rows:
        active_ids = []
        for field in ROLE_FIELDS:
            node_id = (row.get(field) or "").strip()
            if node_id and node_id in node_index:
                active_ids.append(node_id)
        deduped = sorted(set(active_ids))
        for left in range(len(deduped)):
            li = node_index[deduped[left]]
            for right in range(left + 1, len(deduped)):
                ri = node_index[deduped[right]]
                support[li, ri] += 1.0
                support[ri, li] += 1.0
    return support


def build_feature_matrix(
    graph: dict,
    rows: list[dict],
    node_ids: list[str],
    node_index: dict[str, int],
    support: torch.Tensor,
) -> torch.Tensor:
    node_meta = {node["id"]: node for node in graph.get("nodes", [])}
    edge_touch_counts = {node_id: 0.0 for node_id in node_ids}
    for edge in graph.get("edges", []):
        source = edge.get("source")
        target = edge.get("target")
        if source in edge_touch_counts:
            edge_touch_counts[source] += float(edge.get("weight", 1.0))
        if target in edge_touch_counts:
            edge_touch_counts[target] += float(edge.get("weight", 1.0))

    per_node = {
        node_id: {
            "role_counts": {key: 0.0 for key in ROLE_FIELDS.values()},
            "numeric_sums": {key: 0.0 for key in NUMERIC_FIELDS},
            "numeric_counts": {key: 0.0 for key in NUMERIC_FIELDS},
            "conflict_counts": {key: 0.0 for key in CONFLICT_TYPES},
        }
        for node_id in node_ids
    }

    for row in rows:
        conflict_type = normalize_conflict_type(row.get("conflict_type"))
        active_ids = []
        for field, role_name in ROLE_FIELDS.items():
            node_id = (row.get(field) or "").strip()
            if not node_id or node_id not in per_node:
                continue
            per_node[node_id]["role_counts"][role_name] += 1.0
            active_ids.append(node_id)
        for node_id in set(active_ids):
            per_node[node_id]["conflict_counts"][conflict_type] += 1.0
            for numeric_field in NUMERIC_FIELDS:
                value = safe_float(row.get(numeric_field))
                per_node[node_id]["numeric_sums"][numeric_field] += value
                per_node[node_id]["numeric_counts"][numeric_field] += 1.0

    feature_rows = []
    support_degree = support.sum(dim=1)
    total_support = float(max(rows and len(rows) or 1, 1))

    for node_id in node_ids:
        node = node_meta.get(node_id, {})
        node_type = node.get("type", "unknown")
        type_vector = [1.0 if node_type == expected else 0.0 for expected in NODE_TYPES]
        stats = per_node[node_id]
        role_features = [math.log1p(stats["role_counts"][key]) for key in ROLE_FIELDS.values()]
        numeric_features = []
        for numeric_field in NUMERIC_FIELDS:
            count = stats["numeric_counts"][numeric_field]
            mean_value = stats["numeric_sums"][numeric_field] / count if count else 0.0
            numeric_features.append(mean_value)
        conflict_total = sum(stats["conflict_counts"].values()) or 1.0
        conflict_features = [stats["conflict_counts"][key] / conflict_total for key in CONFLICT_TYPES]
        feature_rows.append(
            type_vector
            + [
                math.log1p(float(node.get("event_count", 0.0))),
                math.log1p(edge_touch_counts[node_id]),
                math.log1p(float(support_degree[node_index[node_id]].item())),
                float(support_degree[node_index[node_id]].item()) / total_support,
            ]
            + role_features
            + numeric_features
            + conflict_features
        )

    return torch.tensor(feature_rows, dtype=torch.float32)


def normalize_features(
    features: torch.Tensor,
    *,
    mean: torch.Tensor | None = None,
    std: torch.Tensor | None = None,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    if mean is None:
        mean = features.mean(dim=0, keepdim=True)
    if std is None:
        std = features.std(dim=0, keepdim=True)
    std = torch.where(std < 1e-6, torch.ones_like(std), std)
    return (features - mean) / std, mean, std


def tensors_from_rows(graph: dict, rows: list[dict]) -> tuple[dict, list[dict], list[str], torch.Tensor, torch.Tensor, torch.Tensor]:
    node_ids = [node["id"] for node in graph.get("nodes", [])]
    node_index = {node_id: idx for idx, node_id in enumerate(node_ids)}
    support = build_support_matrix(rows, node_index)
    raw_features = build_feature_matrix(graph, rows, node_ids, node_index, support)
    features, _, _ = normalize_features(raw_features)
    target = build_target_adjacency(graph, node_ids, node_index)
    return graph, rows, node_ids, features, support, target


def load_case_tensors(case: TrainingCase) -> tuple[dict, list[dict], list[str], torch.Tensor, torch.Tensor, torch.Tensor]:
    graph = load_json(case.graph_path)
    rows = read_csv_rows(case.dataset_path)
    return tensors_from_rows(graph, rows)


def rows_for_subset_by_round(case: TrainingCase) -> tuple[list[dict], list[int]]:
    round_summary_path = case.scenario_dir / "round_summary.csv"
    if not round_summary_path.exists():
        raise FileNotFoundError(f"round summary not found for scenario {case.scenario}: {round_summary_path}")

    round_rows = read_round_summary(round_summary_path)
    subset_rows: list[dict] = []
    contributing_rounds: list[int] = []
    remaining = case.subset_size
    for round_entry in round_rows:
        if remaining <= 0:
            break
        round_dataset_path = Path(round_entry["dataset_path"])
        if not round_dataset_path.exists():
            continue
        rows = read_csv_rows(round_dataset_path)
        if not rows:
            continue
        take = min(remaining, len(rows))
        subset_rows.extend(rows[:take])
        contributing_rounds.append(int(round_entry["round"]))
        remaining -= take

    if len(subset_rows) != case.subset_size:
        raise SystemExit(
            f"unable to reconstruct subset rows by rounds for {case.scenario} subset {case.subset_size}: "
            f"expected {case.subset_size}, got {len(subset_rows)}"
        )
    return subset_rows, contributing_rounds


def subset_rows_with_boundaries(case: TrainingCase) -> tuple[list[dict], list[int], list[tuple[int, int, int]]]:
    round_summary = read_round_summary(case.scenario_dir / "round_summary.csv")
    subset_rows: list[dict] = []
    contributing_rounds: list[int] = []
    boundaries: list[tuple[int, int, int]] = []
    remaining = case.subset_size
    offset = 0
    for round_entry in round_summary:
        if remaining <= 0:
            break
        round_dataset_path = Path(round_entry["dataset_path"])
        if not round_dataset_path.exists():
            continue
        rows = read_csv_rows(round_dataset_path)
        if not rows:
            continue
        take = min(remaining, len(rows))
        subset_rows.extend(rows[:take])
        round_number = int(round_entry["round"])
        contributing_rounds.append(round_number)
        boundaries.append((round_number, offset, offset + take))
        offset += take
        remaining -= take
    if len(subset_rows) != case.subset_size:
        raise SystemExit(
            f"unable to reconstruct subset rows by rounds for {case.scenario} subset {case.subset_size}: "
            f"expected {case.subset_size}, got {len(subset_rows)}"
        )
    return subset_rows, contributing_rounds, boundaries


def build_round_split(
    case: TrainingCase,
    test_round_fraction: float,
    min_test_rounds: int,
) -> RoundSplit:
    subset_rows, contributing_rounds, round_boundaries = subset_rows_with_boundaries(case)
    if len(contributing_rounds) < 2:
        raise SystemExit(
            f"round-based split requires at least 2 contributing rounds for {case.scenario} subset {case.subset_size}"
        )

    requested_test_rounds = max(min_test_rounds, int(math.ceil(len(contributing_rounds) * test_round_fraction)))
    num_test_rounds = min(len(contributing_rounds) - 1, requested_test_rounds)
    train_rounds = contributing_rounds[:-num_test_rounds]
    test_rounds = contributing_rounds[-num_test_rounds:]
    train_rows: list[dict[str, Any]] = []
    test_rows: list[dict[str, Any]] = []

    for round_number, start, end in round_boundaries:
        rows = subset_rows[start:end]
        if round_number in train_rounds:
            train_rows.extend(rows)
        elif round_number in test_rounds:
            test_rows.extend(rows)

    if not train_rows or not test_rows:
        raise SystemExit(
            f"round-based split produced an empty partition for {case.scenario} subset {case.subset_size}: "
            f"train_rounds={train_rounds}, test_rounds={test_rounds}"
        )

    return RoundSplit(
        mode="round_holdout",
        train_rows=train_rows,
        test_rows=test_rows,
        train_rounds=train_rounds,
        test_rounds=test_rounds,
        contributing_rounds=contributing_rounds,
    )


def build_manual_round_split(
    case: TrainingCase,
    train_rounds: list[int],
    test_rounds: list[int],
) -> RoundSplit:
    subset_rows, contributing_rounds, round_boundaries = subset_rows_with_boundaries(case)
    contributing_set = set(contributing_rounds)
    train_set = set(train_rounds)
    test_set = set(test_rounds)

    unknown = sorted((train_set | test_set) - contributing_set)
    if unknown:
        raise SystemExit(
            f"manual round split for {case.scenario} subset {case.subset_size} references rounds not present "
            f"in the subset: {unknown}; contributing rounds are {contributing_rounds}"
        )
    if not train_set or not test_set:
        raise SystemExit("manual round split requires non-empty --train-rounds and --test-rounds")
    if train_set & test_set:
        raise SystemExit(f"manual round split has overlapping train/test rounds: {sorted(train_set & test_set)}")

    selected = train_set | test_set
    train_rows: list[dict[str, Any]] = []
    test_rows: list[dict[str, Any]] = []
    selected_rounds: list[int] = []
    for round_number, start, end in round_boundaries:
        if round_number not in selected:
            continue
        selected_rounds.append(round_number)
        rows = subset_rows[start:end]
        if round_number in train_set:
            train_rows.extend(rows)
        elif round_number in test_set:
            test_rows.extend(rows)

    if not train_rows or not test_rows:
        raise SystemExit(
            f"manual round split produced an empty partition for {case.scenario} subset {case.subset_size}: "
            f"train_rounds={sorted(train_set)}, test_rounds={sorted(test_set)}"
        )

    return RoundSplit(
        mode="manual_round_split",
        train_rows=train_rows,
        test_rows=test_rows,
        train_rounds=sorted(train_set),
        test_rounds=sorted(test_set),
        contributing_rounds=selected_rounds,
    )


class DenseGraphSAGELayer(nn.Module):
    def __init__(self, in_dim: int, out_dim: int) -> None:
        super().__init__()
        self.self_linear = nn.Linear(in_dim, out_dim)
        self.neigh_linear = nn.Linear(in_dim, out_dim)

    def forward(self, x: torch.Tensor, support: torch.Tensor) -> torch.Tensor:
        degree = support.sum(dim=1, keepdim=True).clamp(min=1.0)
        neigh = support @ x / degree
        return self.self_linear(x) + self.neigh_linear(neigh)


class GraphSAGEReconstructor(nn.Module):
    def __init__(self, in_dim: int, hidden_dim: int, embed_dim: int, dropout: float) -> None:
        super().__init__()
        self.sage1 = DenseGraphSAGELayer(in_dim, hidden_dim)
        self.sage2 = DenseGraphSAGELayer(hidden_dim, embed_dim)
        self.dropout = dropout
        decoder_dim = embed_dim * 4
        self.decoder = nn.Sequential(
            nn.Linear(decoder_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )

    def encode(self, x: torch.Tensor, support: torch.Tensor) -> torch.Tensor:
        hidden = self.sage1(x, support)
        hidden = F.relu(hidden)
        hidden = F.dropout(hidden, p=self.dropout, training=self.training)
        embedding = self.sage2(hidden, support)
        return F.normalize(embedding, p=2, dim=1)

    def decode(self, embedding: torch.Tensor) -> torch.Tensor:
        n_nodes = embedding.shape[0]
        src = embedding.unsqueeze(1).expand(n_nodes, n_nodes, -1)
        dst = embedding.unsqueeze(0).expand(n_nodes, n_nodes, -1)
        pair_features = torch.cat([src, dst, torch.abs(src - dst), src * dst], dim=-1)
        logits = self.decoder(pair_features).squeeze(-1)
        return logits

    def forward(self, x: torch.Tensor, support: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        embedding = self.encode(x, support)
        return embedding, self.decode(embedding)


def compute_metrics(logits: torch.Tensor, target: torch.Tensor, threshold: float) -> dict:
    mask = ~torch.eye(target.shape[0], dtype=torch.bool, device=target.device)
    probs = torch.sigmoid(logits)
    pred = (probs >= threshold).float()
    target_masked = target[mask]
    pred_masked = pred[mask]

    tp = int(((pred_masked == 1) & (target_masked == 1)).sum().item())
    fp = int(((pred_masked == 1) & (target_masked == 0)).sum().item())
    fn = int(((pred_masked == 0) & (target_masked == 1)).sum().item())
    tn = int(((pred_masked == 0) & (target_masked == 0)).sum().item())
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = (2.0 * precision * recall / (precision + recall)) if (precision + recall) else 0.0

    return {
        "threshold": threshold,
        "tp": tp,
        "fp": fp,
        "fn": fn,
        "tn": tn,
        "precision": round(precision, 6),
        "recall": round(recall, 6),
        "f1": round(f1, 6),
        "predicted_edges": int(pred_masked.sum().item()),
        "target_edges": int(target_masked.sum().item()),
    }


def top_edges(
    logits: torch.Tensor,
    node_ids: list[str],
    target_graph: dict,
    threshold: float,
) -> list[dict]:
    truth = {
        (edge.get("source"), edge.get("target")): edge.get("relation", "unknown")
        for edge in target_graph.get("edges", [])
    }
    probs = torch.sigmoid(logits).detach().cpu()
    edges = []
    for src_idx, source in enumerate(node_ids):
        for dst_idx, target in enumerate(node_ids):
            if src_idx == dst_idx:
                continue
            score = float(probs[src_idx, dst_idx].item())
            if score < threshold:
                continue
            edges.append(
                {
                    "source": source,
                    "target": target,
                    "score": round(score, 6),
                    "baseline_relation": truth.get((source, target)),
                    "is_true_edge": (source, target) in truth,
                }
            )
    edges.sort(key=lambda item: (-item["score"], item["source"], item["target"]))
    return edges


def train_case(
    case: TrainingCase,
    epochs: tuple[int, ...],
    hidden_dim: int,
    embed_dim: int,
    dropout: float,
    learning_rate: float,
    weight_decay: float,
    threshold: float,
    seed: int,
    split_by_rounds: bool,
    test_round_fraction: float,
    min_test_rounds: int,
    manual_train_rounds: list[int] | None,
    manual_test_rounds: list[int] | None,
) -> dict:
    set_seed(seed)
    ensure_dir(case.output_dir)

    graph = load_json(case.graph_path)
    split = None
    if manual_train_rounds or manual_test_rounds:
        if not (manual_train_rounds and manual_test_rounds):
            raise SystemExit("manual round split requires both --train-rounds and --test-rounds")
        split = build_manual_round_split(case, manual_train_rounds, manual_test_rounds)
    elif split_by_rounds:
        split = build_round_split(case, test_round_fraction, min_test_rounds)

    if split is not None:
        node_ids = [node["id"] for node in graph.get("nodes", [])]
        node_index = {node_id: idx for idx, node_id in enumerate(node_ids)}
        train_support = build_support_matrix(split.train_rows, node_index)
        test_support = build_support_matrix(split.test_rows, node_index)
        train_raw = build_feature_matrix(graph, split.train_rows, node_ids, node_index, train_support)
        train_features, feature_mean, feature_std = normalize_features(train_raw)
        test_raw = build_feature_matrix(graph, split.test_rows, node_ids, node_index, test_support)
        test_features, _, _ = normalize_features(test_raw, mean=feature_mean, std=feature_std)
        target = build_target_adjacency(graph, node_ids, node_index)
        train_rows = split.train_rows
        test_rows = split.test_rows
        rows = split.train_rows + split.test_rows
    else:
        _, rows, node_ids, train_features, train_support, target = load_case_tensors(case)
        train_rows = rows
        test_rows = []
        test_features = None
        test_support = None

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    train_features = train_features.to(device)
    train_support = train_support.to(device)
    target = target.to(device)
    if test_features is not None and test_support is not None:
        test_features = test_features.to(device)
        test_support = test_support.to(device)

    model = GraphSAGEReconstructor(
        in_dim=train_features.shape[1],
        hidden_dim=hidden_dim,
        embed_dim=embed_dim,
        dropout=dropout,
    ).to(device)
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=learning_rate,
        weight_decay=weight_decay,
    )

    max_epoch = max(epochs)
    mask = ~torch.eye(target.shape[0], dtype=torch.bool, device=device)
    positives = float(target[mask].sum().item())
    negatives = float(mask.sum().item() - positives)
    pos_weight = torch.tensor(
        [negatives / max(positives, 1.0)],
        dtype=torch.float32,
        device=device,
    )
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

    checkpoints = set(epochs)
    history = []
    best = None
    best_f1 = -1.0
    started_at = time.time()
    checkpoint_dir = case.output_dir / "checkpoints"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    for epoch in range(1, max_epoch + 1):
        model.train()
        optimizer.zero_grad()
        _, train_logits = model(train_features, train_support)
        loss = criterion(train_logits[mask], target[mask])
        loss.backward()
        optimizer.step()

        if epoch not in checkpoints:
            continue

        model.eval()
        with torch.no_grad():
            train_embedding, train_logits = model(train_features, train_support)
            train_metrics = compute_metrics(train_logits, target, threshold)
            eval_embedding = train_embedding
            eval_logits = train_logits
            eval_metrics = train_metrics
            if split_by_rounds and test_features is not None and test_support is not None:
                eval_embedding, eval_logits = model(test_features, test_support)
                eval_metrics = compute_metrics(eval_logits, target, threshold)
            snapshot = {
                "epoch": epoch,
                "loss": round(float(loss.item()), 6),
                **eval_metrics,
                "train_precision": train_metrics["precision"],
                "train_recall": train_metrics["recall"],
                "train_f1": train_metrics["f1"],
                "train_tp": train_metrics["tp"],
                "train_fp": train_metrics["fp"],
                "train_fn": train_metrics["fn"],
                "train_tn": train_metrics["tn"],
            }
            history.append(snapshot)
            torch.save(
                {
                    "state_dict": model.state_dict(),
                    "node_ids": node_ids,
                    "feature_dim": int(train_features.shape[1]),
                    "hidden_dim": hidden_dim,
                    "embed_dim": embed_dim,
                    "dropout": dropout,
                    "threshold": threshold,
                    "epoch": epoch,
                },
                checkpoint_dir / f"epoch_{epoch}.pt",
            )
            if eval_metrics["f1"] >= best_f1:
                best_f1 = eval_metrics["f1"]
                best = {
                    "epoch": epoch,
                    "metrics": eval_metrics,
                    "train_metrics": train_metrics,
                    "embedding": eval_embedding.detach().cpu(),
                    "logits": eval_logits.detach().cpu(),
                }

    best_edges = top_edges(best["logits"], node_ids, graph, threshold) if best else []
    torch.save(
        {
            "state_dict": model.state_dict(),
            "node_ids": node_ids,
            "feature_dim": int(train_features.shape[1]),
            "hidden_dim": hidden_dim,
            "embed_dim": embed_dim,
            "dropout": dropout,
            "threshold": threshold,
            "best_epoch": best["epoch"] if best else None,
        },
        case.output_dir / "best_model.pt",
    )

    summary = {
        "scenario": case.scenario,
        "subset_size": case.subset_size,
        "dataset_path": str(case.dataset_path),
        "graph_path": str(case.graph_path),
        "output_dir": str(case.output_dir),
        "device": str(device),
        "rows": len(rows),
        "train_rows": len(train_rows),
        "test_rows": len(test_rows),
        "nodes": len(node_ids),
        "target_edges": int(target.sum().item()),
        "feature_dim": int(train_features.shape[1]),
        "epochs_requested": list(epochs),
        "elapsed_seconds": round(time.time() - started_at, 3),
        "split_mode": split.mode if split else "none",
        "train_rounds": split.train_rounds if split else [],
        "test_rounds": split.test_rounds if split else [],
        "contributing_rounds": split.contributing_rounds if split else [],
        "best_epoch": best["epoch"] if best else None,
        "best_metrics": best["metrics"] if best else {},
        "train_metrics_at_best": best["train_metrics"] if best else {},
        "history": history,
        "predicted_edges_at_best": best_edges[:50],
    }
    with (case.output_dir / "training_summary.json").open("w") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)

    with (case.output_dir / "history.csv").open("w", newline="") as f:
        fieldnames = [
            "epoch",
            "loss",
            "precision",
            "recall",
            "f1",
            "tp",
            "fp",
            "fn",
            "tn",
            "predicted_edges",
            "target_edges",
            "threshold",
            "train_precision",
            "train_recall",
            "train_f1",
            "train_tp",
            "train_fp",
            "train_fn",
            "train_tn",
        ]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(history)

    return summary


def main() -> int:
    args = parse_args()
    experiment_dir = Path(args.experiment_dir) if args.experiment_dir else latest_experiment_dir(DEFAULT_EXPERIMENT_ROOT)
    output_root = Path(args.output_dir) if args.output_dir else experiment_dir / DEFAULT_OUTPUT_STEM
    ensure_dir(output_root)

    epochs = parse_int_tuple(args.epochs)
    subset_sizes = parse_int_tuple(args.subset_sizes)
    manual_train_rounds = parse_round_list(args.train_rounds) if args.train_rounds else None
    manual_test_rounds = parse_round_list(args.test_rounds) if args.test_rounds else None
    if (manual_train_rounds is None) != (manual_test_rounds is None):
        raise SystemExit("use both --train-rounds and --test-rounds together")
    reports = selected_reports(experiment_dir, args.scenarios)
    cases = build_cases(experiment_dir, reports, subset_sizes, output_root)

    aggregate = {
        "generated_at": int(time.time()),
        "generated_at_iso": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "experiment_dir": str(experiment_dir),
        "output_root": str(output_root),
        "epochs": list(epochs),
        "subset_sizes": list(subset_sizes),
        "threshold": args.threshold,
        "split_by_rounds": args.split_by_rounds,
        "test_round_fraction": args.test_round_fraction,
        "min_test_rounds": args.min_test_rounds,
        "train_rounds": manual_train_rounds or [],
        "test_rounds": manual_test_rounds or [],
        "cases": [],
    }

    print(f"Experimento de treino: {experiment_dir}")
    print(f"Saída do GraphSAGE: {output_root}")
    print(f"Epochs: {', '.join(str(value) for value in epochs)}")
    print(f"Subsets: {', '.join(str(value) for value in subset_sizes)}")
    if manual_train_rounds and manual_test_rounds:
        print(f"Split manual de rodadas: treino={manual_train_rounds} | teste={manual_test_rounds}")
    else:
        print(f"Split por rodadas: {'sim' if args.split_by_rounds else 'não'}")

    for case in cases:
        print(f"\n=== {case.scenario} | subset {case.subset_size} ===")
        summary = train_case(
            case=case,
            epochs=epochs,
            hidden_dim=args.hidden_dim,
            embed_dim=args.embed_dim,
            dropout=args.dropout,
            learning_rate=args.learning_rate,
            weight_decay=args.weight_decay,
            threshold=args.threshold,
            seed=args.seed,
            split_by_rounds=args.split_by_rounds,
            test_round_fraction=args.test_round_fraction,
            min_test_rounds=args.min_test_rounds,
            manual_train_rounds=manual_train_rounds,
            manual_test_rounds=manual_test_rounds,
        )
        aggregate["cases"].append(summary)
        best = summary.get("best_metrics", {})
        if args.split_by_rounds or (manual_train_rounds and manual_test_rounds):
            train_best = summary.get("train_metrics_at_best", {})
            print(
                "best_epoch={best_epoch} | test_f1={test_f1:.4f} | test_precision={test_precision:.4f} | "
                "test_recall={test_recall:.4f} | train_f1={train_f1:.4f} | "
                "train_rounds={train_rounds} | test_rounds={test_rounds}".format(
                    best_epoch=summary.get("best_epoch"),
                    test_f1=best.get("f1", 0.0),
                    test_precision=best.get("precision", 0.0),
                    test_recall=best.get("recall", 0.0),
                    train_f1=train_best.get("f1", 0.0),
                    train_rounds=summary.get("train_rounds", []),
                    test_rounds=summary.get("test_rounds", []),
                )
            )
        else:
            print(
                "best_epoch={best_epoch} | f1={f1:.4f} | precision={precision:.4f} | "
                "recall={recall:.4f}".format(
                    best_epoch=summary.get("best_epoch"),
                    f1=best.get("f1", 0.0),
                    precision=best.get("precision", 0.0),
                    recall=best.get("recall", 0.0),
                )
            )

    aggregate_path = output_root / "aggregate_report.json"
    with aggregate_path.open("w") as f:
        json.dump(aggregate, f, indent=2, ensure_ascii=False)

    print(f"\nRelatório agregado: {aggregate_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
