{
 "title": "per_UE_stats",
 "time": { "from": "now-48h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Serving Cell ID (UE)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "UE 1",
     "query": "SELECT \"value\" FROM \"ue_position_cell_1\" WHERE $timeFilter"
    },
    {
     "alias": "UE 2",
     "query": "SELECT \"value\" FROM \"ue_position_cell_2\" WHERE $timeFilter"
    },
    {
     "alias": "UE 3",
     "query": "SELECT \"value\" FROM \"ue_position_cell_3\" WHERE $timeFilter"
    },
    {
     "alias": "UE 4",
     "query": "SELECT \"value\" FROM \"ue_position_cell_4\" WHERE $timeFilter"
    },
    {
     "alias": "UE 5",
     "query": "SELECT \"value\" FROM \"ue_position_cell_5\" WHERE $timeFilter"
    },
    {
     "alias": "UE 6",
     "query": "SELECT \"value\" FROM \"ue_position_cell_6\" WHERE $timeFilter"
    },
    {
     "alias": "UE 7",
     "query": "SELECT \"value\" FROM \"ue_position_cell_7\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Serving SINR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "alias": "UE 1",
     "query": "SELECT \"value\" FROM \"ue_1_l3 serving sinr\" WHERE $timeFilter"
    },
    {
     "alias": "UE 2",
     "query": "SELECT \"value\" FROM \"ue_2_l3 serving sinr\" WHERE $timeFilter"
    },
    {
     "alias": "UE 3",
     "query": "SELECT \"value\" FROM \"ue_3_l3 serving sinr\" WHERE $timeFilter"
    },
    {
     "alias": "UE 4",
     "query": "SELECT \"value\" FROM \"ue_4_l3 serving sinr\" WHERE $timeFilter"
    },
    {
     "alias": "UE 5",
     "query": "SELECT \"value\" FROM \"ue_5_l3 serving sinr\" WHERE $timeFilter"
    },
    {
     "alias": "UE 6",
     "query": "SELECT \"value\" FROM \"ue_6_l3 serving sinr\" WHERE $timeFilter"
    },
    {
     "alias": "UE 7",
     "query": "SELECT \"value\" FROM \"ue_7_l3 serving sinr\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "QoS Flow (PDCP PDU Volume DL)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "UE 1",
     "query": "SELECT \"value\" FROM \"ue_1_qosflow.pdcppduvolumedl_filter\" WHERE $timeFilter"
    },
    {
     "alias": "UE 2",
     "query": "SELECT \"value\" FROM \"ue_2_qosflow.pdcppduvolumedl_filter\" WHERE $timeFilter"
    },
    {
     "alias": "UE 3",
     "query": "SELECT \"value\" FROM \"ue_3_qosflow.pdcppduvolumedl_filter\" WHERE $timeFilter"
    },
    {
     "alias": "UE 4",
     "query": "SELECT \"value\" FROM \"ue_4_qosflow.pdcppduvolumedl_filter\" WHERE $timeFilter"
    },
    {
     "alias": "UE 5",
     "query": "SELECT \"value\" FROM \"ue_5_qosflow.pdcppduvolumedl_filter\" WHERE $timeFilter"
    },
    {
     "alias": "UE 6",
     "query": "SELECT \"value\" FROM \"ue_6_qosflow.pdcppduvolumedl_filter\" WHERE $timeFilter"
    },
    {
     "alias": "UE 7",
     "query": "SELECT \"value\" FROM \"ue_7_qosflow.pdcppduvolumedl_filter\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "PRB Used DL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 9 },
   "targets": [
    {
     "alias": "UE 1",
     "query": "SELECT \"value\" FROM \"ue_1_rru.prbuseddl\" WHERE $timeFilter"
    },
    {
     "alias": "UE 2",
     "query": "SELECT \"value\" FROM \"ue_2_rru.prbuseddl\" WHERE $timeFilter"
    },
    {
     "alias": "UE 3",
     "query": "SELECT \"value\" FROM \"ue_3_rru.prbuseddl\" WHERE $timeFilter"
    },
    {
     "alias": "UE 4",
     "query": "SELECT \"value\" FROM \"ue_4_rru.prbuseddl\" WHERE $timeFilter"
    },
    {
     "alias": "UE 5",
     "query": "SELECT \"value\" FROM \"ue_5_rru.prbuseddl\" WHERE $timeFilter"
    },
    {
     "alias": "UE 6",
     "query": "SELECT \"value\" FROM \"ue_6_rru.prbuseddl\" WHERE $timeFilter"
    },
    {
     "alias": "UE 7",
     "query": "SELECT \"value\" FROM \"ue_7_rru.prbuseddl\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Number of DL Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "UE 1",
     "query": "SELECT \"value\" FROM \"ue_1_tb.errtotalnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 2",
     "query": "SELECT \"value\" FROM \"ue_2_tb.errtotalnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 3",
     "query": "SELECT \"value\" FROM \"ue_3_tb.errtotalnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 4",
     "query": "SELECT \"value\" FROM \"ue_4_tb.errtotalnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 5",
     "query": "SELECT \"value\" FROM \"ue_5_tb.errtotalnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 6",
     "query": "SELECT \"value\" FROM \"ue_6_tb.errtotalnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 7",
     "query": "SELECT \"value\" FROM \"ue_7_tb.errtotalnbrdl.1.ueid\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Number of DL TB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 17 },
   "targets": [
    {
     "alias": "UE 1",
     "query": "SELECT \"value\" FROM \"ue_1_tb.totnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 2",
     "query": "SELECT \"value\" FROM \"ue_2_tb.totnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 3",
     "query": "SELECT \"value\" FROM \"ue_3_tb.totnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 4",
     "query": "SELECT \"value\" FROM \"ue_4_tb.totnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 5",
     "query": "SELECT \"value\" FROM \"ue_5_tb.totnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 6",
     "query": "SELECT \"value\" FROM \"ue_6_tb.totnbrdl.1.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 7",
     "query": "SELECT \"value\" FROM \"ue_7_tb.totnbrdl.1.ueid\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Number of DL Initial TB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "UE 1",
     "query": "SELECT \"value\" FROM \"ue_1_tb.totnbrdlinitial\" WHERE $timeFilter"
    },
    {
     "alias": "UE 2",
     "query": "SELECT \"value\" FROM \"ue_2_tb.totnbrdlinitial\" WHERE $timeFilter"
    },
    {
     "alias": "UE 3",
     "query": "SELECT \"value\" FROM \"ue_3_tb.totnbrdlinitial\" WHERE $timeFilter"
    },
    {
     "alias": "UE 4",
     "query": "SELECT \"value\" FROM \"ue_4_tb.totnbrdlinitial\" WHERE $timeFilter"
    },
    {
     "alias": "UE 5",
     "query": "SELECT \"value\" FROM \"ue_5_tb.totnbrdlinitial\" WHERE $timeFilter"
    },
    {
     "alias": "UE 6",
     "query": "SELECT \"value\" FROM \"ue_6_tb.totnbrdlinitial\" WHERE $timeFilter"
    },
    {
     "alias": "UE 7",
     "query": "SELECT \"value\" FROM \"ue_7_tb.totnbrdlinitial\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DL PRB Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 25 },
   "targets": [
    {
     "alias": "UE 1",
     "query": "SELECT \"value\" FROM \"ue_1_dlprbusage\" WHERE $timeFilter"
    },
    {
     "alias": "UE 2",
     "query": "SELECT \"value\" FROM \"ue_2_dlprbusage\" WHERE $timeFilter"
    },
    {
     "alias": "UE 3",
     "query": "SELECT \"value\" FROM \"ue_3_dlprbusage\" WHERE $timeFilter"
    },
    {
     "alias": "UE 4",
     "query": "SELECT \"value\" FROM \"ue_4_dlprbusage\" WHERE $timeFilter"
    },
    {
     "alias": "UE 5",
     "query": "SELECT \"value\" FROM \"ue_5_dlprbusage\" WHERE $timeFilter"
    },
    {
     "alias": "UE 6",
     "query": "SELECT \"value\" FROM \"ue_6_dlprbusage\" WHERE $timeFilter"
    },
    {
     "alias": "UE 7",
     "query": "SELECT \"value\" FROM \"ue_7_dlprbusage\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB Buffer Size Qos",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 32 },
   "targets": [
    {
     "alias": "UE 1",
     "query": "SELECT \"value\" FROM \"ue_1_drb.buffersize.qos.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 2",
     "query": "SELECT \"value\" FROM \"ue_2_drb.buffersize.qos.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 3",
     "query": "SELECT \"value\" FROM \"ue_3_drb.buffersize.qos.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 4",
     "query": "SELECT \"value\" FROM \"ue_4_drb.buffersize.qos.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 5",
     "query": "SELECT \"value\" FROM \"ue_5_drb.buffersize.qos.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 6",
     "query": "SELECT \"value\" FROM \"ue_6_drb.buffersize.qos.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 7",
     "query": "SELECT \"value\" FROM \"ue_7_drb.buffersize.qos.ueid\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB Throughput (PDCP Based)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 32 },
   "targets": [
    {
     "alias": "UE 1",
     "query": "SELECT \"value\" FROM \"ue_1_drb.uethpdlpdcpbased.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 2",
     "query": "SELECT \"value\" FROM \"ue_2_drb.uethpdlpdcpbased.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 3",
     "query": "SELECT \"value\" FROM \"ue_3_drb.uethpdlpdcpbased.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 4",
     "query": "SELECT \"value\" FROM \"ue_4_drb.uethpdlpdcpbased.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 5",
     "query": "SELECT \"value\" FROM \"ue_5_drb.uethpdlpdcpbased.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 6",
     "query": "SELECT \"value\" FROM \"ue_6_drb.uethpdlpdcpbased.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 7",
     "query": "SELECT \"value\" FROM \"ue_7_drb.uethpdlpdcpbased.ueid\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB Throughput (UE ID)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 39 },
   "targets": [
    {
     "alias": "UE 1",
     "query": "SELECT \"value\" FROM \"ue_1_drb.uethpdl.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 2",
     "query": "SELECT \"value\" FROM \"ue_2_drb.uethpdl.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 3",
     "query": "SELECT \"value\" FROM \"ue_3_drb.uethpdl.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 4",
     "query": "SELECT \"value\" FROM \"ue_4_drb.uethpdl.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 5",
     "query": "SELECT \"value\" FROM \"ue_5_drb.uethpdl.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 6",
     "query": "SELECT \"value\" FROM \"ue_6_drb.uethpdl.ueid\" WHERE $timeFilter"
    },
    {
     "alias": "UE 7",
     "query": "SELECT \"value\" FROM \"ue_7_drb.uethpdl.ueid\" WHERE $timeFilter"
    }
   ]
  }
 ]
}