#!/usr/bin/env bash
set -euo pipefail

# Rodada GreenRAN real-only com ARMD + TA-SAM em canário conjunto.
# O TA-SAM controla somente a divisão RAN/IA em 10% das decisões elegíveis;
# ARMD mantém a proteção energética/SLA e o live allocator é o fallback.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

export GREENRAN_STATE_DIR="${GREENRAN_STATE_DIR:-$PROJECT_ROOT/runs/greenran_tasam_joint_control_wall10m_20260810}"
export GREENRAN_FIXED_SCENARIO_CONFIG="${GREENRAN_FIXED_SCENARIO_CONFIG:-$PROJECT_ROOT/config/greenran_fixed_scenario.json}"
export GREENRAN_SIM_TIME="${GREENRAN_SIM_TIME:-100000}"
export GREENRAN_WALL_TIME_LIMIT_SECONDS="${GREENRAN_WALL_TIME_LIMIT_SECONDS:-600}"
export GREENRAN_WALL_KEEP_RIC="${GREENRAN_WALL_KEEP_RIC:-1}"
export GREENRAN_CLEAN_SCOPE="${GREENRAN_CLEAN_SCOPE:-instance}"
# Keep the healthy no-event round as the default, but allow an authorized
# collection run to select a frozen event profile explicitly.  The event
# alternator injects documented service stages; it never replaces PDCP
# measurements, and proxy latency remains disabled below.
export GREENRAN_COLLECTION_EVENT_PROFILE="${GREENRAN_COLLECTION_EVENT_PROFILE:-none}"
export GREENRAN_COLLECTION_DISABLE_APP_OVERRIDES="${GREENRAN_COLLECTION_DISABLE_APP_OVERRIDES:-1}"
export GREENRAN_RAN_PRESSURE_PROFILE="greenran_autonomous_priority_wall10m_v1"
export GREENRAN_RAN_PRESSURE_TIME_SOURCE="wall"
export GREENRAN_REAL_ONLY="1"
export GREENRAN_REQUIRE_REAL_PDCP="1"
export GREENRAN_START_RIC="${GREENRAN_START_RIC:-0}"

export GREENRAN_NS3_UE_COUNT="${GREENRAN_NS3_UE_COUNT:-20}"
export GREENRAN_NS3_CAMERA_UE_COUNT="${GREENRAN_NS3_CAMERA_UE_COUNT:-3}"
export GREENRAN_NS3_VEHICLE_UE_COUNT="${GREENRAN_NS3_VEHICLE_UE_COUNT:-5}"
export GREENRAN_NS3_MMWAVE_ENB_NODES="${GREENRAN_NS3_MMWAVE_ENB_NODES:-3}"
export GREENRAN_NS3_VEHICLE_PACKET_SIZE_BYTES="${GREENRAN_NS3_VEHICLE_PACKET_SIZE_BYTES:-800}"
export GREENRAN_NS3_VEHICLE_PACKET_INTERVAL_US="${GREENRAN_NS3_VEHICLE_PACKET_INTERVAL_US:-4000}"
export GREENRAN_NS3_CAMERA_PACKET_SIZE_BYTES="${GREENRAN_NS3_CAMERA_PACKET_SIZE_BYTES:-1000}"
export GREENRAN_NS3_CAMERA_PACKET_INTERVAL_US="${GREENRAN_NS3_CAMERA_PACKET_INTERVAL_US:-320}"
export GREENRAN_NS3_UE_SPEED_MIN="${GREENRAN_NS3_UE_SPEED_MIN:-10}"
export GREENRAN_NS3_UE_SPEED_MAX="${GREENRAN_NS3_UE_SPEED_MAX:-20}"
export GREENRAN_NS3_USE_MC_UE_DEVICES="${GREENRAN_NS3_USE_MC_UE_DEVICES:-false}"
export GREENRAN_NS3_E2NR_ENABLED="${GREENRAN_NS3_E2NR_ENABLED:-true}"
export GREENRAN_NS3_E2DU_ENABLED="${GREENRAN_NS3_E2DU_ENABLED:-true}"
export GREENRAN_NS3_E2CUUP_ENABLED="${GREENRAN_NS3_E2CUUP_ENABLED:-false}"
export GREENRAN_NS3_E2CUCP_ENABLED="${GREENRAN_NS3_E2CUCP_ENABLED:-false}"
export GREENRAN_NS3_ENABLE_TRACES="${GREENRAN_NS3_ENABLE_TRACES:-1}"

# TA-SAM + ARMD joint control trial: approved gate, 10% canary, rollback.
CONTROL_TRIAL_ROOT="$PROJECT_ROOT/runs/tasam_greenran_control_trial_20260809"
export GREENRAN_TASAM_ADVISOR_ENABLED="1"
export GREENRAN_TASAM_ADVISOR_MODE="control_trial"
export GREENRAN_TASAM_EVAL_MANIFEST="${GREENRAN_TASAM_EVAL_MANIFEST:-$CONTROL_TRIAL_ROOT/tasam_candidate_evaluation.json}"
export GREENRAN_MARL_CONTROL_GATE_MANIFEST="${GREENRAN_MARL_CONTROL_GATE_MANIFEST:-$CONTROL_TRIAL_ROOT/marl_control_gate.json}"
export GREENRAN_CONTROL_TRIAL_ENABLED="1"
export GREENRAN_CONTROL_TRIAL_FRACTION="${GREENRAN_CONTROL_TRIAL_FRACTION:-0.10}"
export GREENRAN_CONTROL_TRIAL_TARGET_DECISIONS="${GREENRAN_CONTROL_TRIAL_TARGET_DECISIONS:-300}"
export GREENRAN_CONTROL_TRIAL_ROLLING_WINDOW="${GREENRAN_CONTROL_TRIAL_ROLLING_WINDOW:-30}"
export GREENRAN_CONTROL_TRIAL_CRITICAL_STREAK="${GREENRAN_CONTROL_TRIAL_CRITICAL_STREAK:-3}"
export GREENRAN_CONTROL_TRIAL_MIN_CONFIDENCE="${GREENRAN_CONTROL_TRIAL_MIN_CONFIDENCE:-0.60}"
export GREENRAN_CONTROL_TRIAL_MIN_RAN_DELTA="${GREENRAN_CONTROL_TRIAL_MIN_RAN_DELTA:--0.01}"
export GREENRAN_CONTROL_TRIAL_MIN_AI_DELTA="${GREENRAN_CONTROL_TRIAL_MIN_AI_DELTA:--0.01}"
export GREENRAN_CONTROL_TRIAL_STATE="${GREENRAN_CONTROL_TRIAL_STATE:-$GREENRAN_STATE_DIR/control_trial_state.json}"
export GREENRAN_TASAM_EXPORT_ALLOW_PROXY="0"
export GREENRAN_TASAM_TRUE_ONLINE_ENABLED="0"
export GREENRAN_ML_RETRAIN_ENABLED="false"
export GREENRAN_PDCP_STALE_SECONDS="600"

exec "$SCRIPT_DIR/run_greenran_tasam_3du_collection.sh"
