#!/usr/bin/env bash
set -euo pipefail

# GreenRAN adaptation collection: canonical 20-UE/3-DU topology.  The
# article/ns-3 collection remains a separate 200-UE/6-DU track.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

export GREENRAN_STATE_DIR="${GREENRAN_STATE_DIR:-$PROJECT_ROOT/runs/greenran_tasam_3du_collection}"
export GREENRAN_FIXED_SCENARIO_CONFIG="${GREENRAN_FIXED_SCENARIO_CONFIG:-$PROJECT_ROOT/config/greenran_fixed_scenario.json}"
export GREENRAN_REAL_ONLY_NS3_UE_COUNT="${GREENRAN_REAL_ONLY_NS3_UE_COUNT:-20}"
export GREENRAN_REAL_ONLY_NS3_CAMERA_UE_COUNT="${GREENRAN_REAL_ONLY_NS3_CAMERA_UE_COUNT:-3}"
export GREENRAN_REAL_ONLY_NS3_VEHICLE_UE_COUNT="${GREENRAN_REAL_ONLY_NS3_VEHICLE_UE_COUNT:-5}"
export GREENRAN_NS3_UE_COUNT="${GREENRAN_NS3_UE_COUNT:-20}"
export GREENRAN_NS3_CAMERA_UE_COUNT="${GREENRAN_NS3_CAMERA_UE_COUNT:-3}"
export GREENRAN_NS3_VEHICLE_UE_COUNT="${GREENRAN_NS3_VEHICLE_UE_COUNT:-5}"
export GREENRAN_NS3_MMWAVE_ENB_NODES="${GREENRAN_NS3_MMWAVE_ENB_NODES:-3}"
export GREENRAN_TASAM_TRUE_ONLINE_ENABLED="${GREENRAN_TASAM_TRUE_ONLINE_ENABLED:-0}"
export GREENRAN_ML_RETRAIN_ENABLED="${GREENRAN_ML_RETRAIN_ENABLED:-false}"
export GREENRAN_COLLECTION_EVENT_PROFILE="${GREENRAN_COLLECTION_EVENT_PROFILE:-tasam_training_balanced_v1}"
export GREENRAN_COLLECTION_DISABLE_APP_OVERRIDES="${GREENRAN_COLLECTION_DISABLE_APP_OVERRIDES:-0}"
export GREENRAN_TASAM_EXPORT_ALLOW_PROXY="${GREENRAN_TASAM_EXPORT_ALLOW_PROXY:-1}"
export GREENRAN_TASAM_TRAINABLE_PROFILE="${GREENRAN_TASAM_TRAINABLE_PROFILE:-rapp_online_controlled_trainable}"
export GREENRAN_REQUIRE_REAL_PDCP="${GREENRAN_REQUIRE_REAL_PDCP:-0}"
export GREENRAN_START_RIC="${GREENRAN_START_RIC:-1}"
# The GreenRAN line-2 collector must receive real PDCP/E2 observations.  The
# article reproduction keeps its conservative E2 defaults in the parent script.
export GREENRAN_NS3_E2NR_ENABLED="${GREENRAN_NS3_E2NR_ENABLED:-true}"
export GREENRAN_NS3_E2DU_ENABLED="${GREENRAN_NS3_E2DU_ENABLED:-true}"
export GREENRAN_NS3_E2CUUP_ENABLED="${GREENRAN_NS3_E2CUUP_ENABLED:-false}"
export GREENRAN_NS3_E2CUCP_ENABLED="${GREENRAN_NS3_E2CUCP_ENABLED:-false}"
export GREENRAN_TASAM_EXPORT_INTERVAL="${GREENRAN_TASAM_EXPORT_INTERVAL:-60}"

exec "$SCRIPT_DIR/run_tasam_article_ns3_collection.sh"
