#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

export GREENRAN_DISABLE_RIC="${GREENRAN_DISABLE_RIC:-1}"
export GREENRAN_ENABLE_MONITORING_STACK="${GREENRAN_ENABLE_MONITORING_STACK:-0}"
export GREENRAN_COLLECTION_EVENT_PROFILE="${GREENRAN_COLLECTION_EVENT_PROFILE:-drl_article_conflict_smoke_v1}"
export GREENRAN_COLLECTION_EVENT_CYCLES="${GREENRAN_COLLECTION_EVENT_CYCLES:-1}"
export GREENRAN_SIM_TIME="${GREENRAN_SIM_TIME:-90}"
export GREENRAN_ENABLE_MARL_GATE_WATCHER="${GREENRAN_ENABLE_MARL_GATE_WATCHER:-1}"

echo "[GREENRAN_STABLE] starting scenario in stable no-RIC mode"
echo "[GREENRAN_STABLE] state_dir=${GREENRAN_STATE_DIR:-/tmp} sim_time=${GREENRAN_SIM_TIME} profile=${GREENRAN_COLLECTION_EVENT_PROFILE}"

bash scripts/run_greenran_v2.sh
