#!/usr/bin/env python3
"""
Summarize DRL predictor trace JSONL files.

Expected input: one JSON object per line, as generated by src/rapp_drl_predictor.py
when GREENRAN_DRL_TRACE=1.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Summarize GreenRAN DRL trace JSONL.")
    parser.add_argument(
        "--trace-file",
        default="/tmp/drl_predictor_trace.jsonl",
        help="path to the JSONL trace file generated by GREENRAN_DRL_TRACE",
    )
    parser.add_argument(
        "--output-json",
        help="optional path to save the summary JSON",
    )
    return parser.parse_args()


def safe_float(value) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def mean(values: list[float]) -> float:
    return sum(values) / len(values) if values else 0.0


def load_trace(path: Path) -> list[dict]:
    items = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            text = line.strip()
            if not text:
                continue
            items.append(json.loads(text))
    return items


def summarize(items: list[dict]) -> dict:
    final_decisions = Counter()
    actor_decisions = Counter()
    policy_actions = Counter()
    risk_bands = Counter()
    calibrated_count = 0
    hysteresis_count = 0

    confidence_by_decision: dict[str, list[float]] = defaultdict(list)
    actor_confidence_by_decision: dict[str, list[float]] = defaultdict(list)
    cvar_by_decision: dict[str, list[float]] = defaultdict(list)
    risk_by_decision: dict[str, list[float]] = defaultdict(list)
    raw_minus_final: list[float] = []

    for item in items:
        output = item.get("output", {})
        final_decision = output.get("final_decision", "UNKNOWN")
        actor_decision = output.get("a3c_decision", "UNKNOWN")
        policy_action = output.get("policy_action", "UNKNOWN")
        risk_band = output.get("risk_band", "unknown")

        final_decisions[final_decision] += 1
        actor_decisions[actor_decision] += 1
        policy_actions[policy_action] += 1
        risk_bands[risk_band] += 1

        if output.get("calibrated"):
            calibrated_count += 1
        if output.get("hysteresis_applied"):
            hysteresis_count += 1

        confidence_by_decision[final_decision].append(safe_float(output.get("confidence")))
        actor_confidence_by_decision[final_decision].append(safe_float(output.get("actor_confidence")))
        cvar_by_decision[final_decision].append(safe_float(output.get("predicted_cvar_ms")))
        risk_by_decision[final_decision].append(safe_float(output.get("risk_score")))
        raw_minus_final.append(
            safe_float(output.get("raw_predicted_cvar_ms")) - safe_float(output.get("predicted_cvar_ms"))
        )

    total = len(items)
    summary = {
        "total_cycles": total,
        "final_decisions": dict(final_decisions),
        "actor_decisions": dict(actor_decisions),
        "policy_actions": dict(policy_actions),
        "risk_bands": dict(risk_bands),
        "calibrated_cycles": calibrated_count,
        "calibrated_ratio": calibrated_count / total if total else 0.0,
        "hysteresis_cycles": hysteresis_count,
        "hysteresis_ratio": hysteresis_count / total if total else 0.0,
        "avg_raw_minus_final_cvar_ms": mean(raw_minus_final),
        "decision_stats": {},
    }

    all_decisions = sorted(set(final_decisions) | set(actor_decisions))
    for decision in all_decisions:
        summary["decision_stats"][decision] = {
            "count": final_decisions.get(decision, 0),
                "avg_confidence": mean(confidence_by_decision[decision]),
                "avg_actor_confidence": mean(actor_confidence_by_decision[decision]),
                "avg_predicted_cvar_ms": mean(cvar_by_decision[decision]),
                "avg_risk_score": mean(risk_by_decision[decision]),
            }

    return summary


def print_summary(summary: dict) -> None:
    print("DRL trace summary")
    print("=================")
    print(f"total_cycles: {summary['total_cycles']}")
    print(f"final_decisions: {summary['final_decisions']}")
    print(f"actor_decisions: {summary['actor_decisions']}")
    print(f"policy_actions: {summary['policy_actions']}")
    print(f"risk_bands: {summary['risk_bands']}")
    print(
        f"calibrated: {summary['calibrated_cycles']} "
        f"({summary['calibrated_ratio']:.1%})"
    )
    print(
        f"hysteresis: {summary['hysteresis_cycles']} "
        f"({summary['hysteresis_ratio']:.1%})"
    )
    print(f"avg_raw_minus_final_cvar_ms: {summary['avg_raw_minus_final_cvar_ms']:.2f}")
    print()
    print("decision stats")
    for decision, stats in summary["decision_stats"].items():
        print(
            f"- {decision}: "
            f"count={stats['count']} | "
            f"avg_conf={stats['avg_confidence']:.2f} | "
            f"avg_actor_conf={stats['avg_actor_confidence']:.2f} | "
            f"avg_pred_cvar={stats['avg_predicted_cvar_ms']:.2f}ms | "
            f"avg_risk={stats['avg_risk_score']:.2f}"
        )


def main() -> int:
    args = parse_args()
    trace_path = Path(args.trace_file)
    if not trace_path.exists():
        raise SystemExit(f"trace file not found: {trace_path}")

    items = load_trace(trace_path)
    summary = summarize(items)
    print_summary(summary)

    if args.output_json:
        output_path = Path(args.output_json)
        output_path.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"\nsummary_json: {output_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
